import type { EmojiCategory, EmojiDefinition } from '@/context/GameContext';

export const MIN_EMOJI_COST = 120;
export const MAX_EMOJI_COST = 1_000_000_000;

// Heavily skewed distribution: 80% below 100M, only top 5% near 1B
const clampPercent = (value: number) => Math.min(Math.max(value, 0), 1);

// Use exponential curve for heavily skewed distribution
// Power of 4.3 ensures 80% of items stay below 100M
export const computeBellCurveCost = (percent: number) => {
  const p = clampPercent(percent);
  
  // Apply exponential curve with power of 4.3
  // At p=0.8: 0.8^4.3 ≈ 0.327, which maps to ~327M
  // Adjusting to get 80% under 100M
  const skewed = Math.pow(p, 4.3);
  
  // Map to price range
  const cost = MIN_EMOJI_COST + skewed * (MAX_EMOJI_COST - MIN_EMOJI_COST);
  return Math.round(cost);
};

const PRICE_ANCHORS: Record<string, number> = {};

const createEmoji = (
  definition: Omit<EmojiDefinition, 'tags' | 'popularity' | 'cost'> & {
    tags: (string | { keyword: string; aliases?: string[] })[];
    popularity: number;
    cost?: number;
    priceAnchorPercent?: number;
  }
): EmojiDefinition => {
  const normalizedTags = definition.tags.flatMap((entry) => {
    if (typeof entry === 'string') {
      return entry;
    }

    const { keyword, aliases = [] } = entry;
    return [keyword, ...aliases];
  });

  if (typeof definition.priceAnchorPercent === 'number') {
    PRICE_ANCHORS[definition.id] = clampPercent(definition.priceAnchorPercent);
  }

  return {
    id: definition.id,
    emoji: definition.emoji,
    name: definition.name,
    cost: definition.cost ?? MIN_EMOJI_COST,
    category: definition.category,
    tags: Array.from(new Set(normalizedTags)),
    popularity: definition.popularity,
  };
};

const baseGardenEmojiEntries: EmojiDefinition[] = [
  createEmoji({
    id: 'sunflower-bloom',
    emoji: '🌻',
    name: 'Sunflower Bloom',
    cost: 75,
    category: 'plants',
    popularity: 1,
    tags: [
      { keyword: 'sunflower', aliases: ['sunny bloom', 'helios flower', 'yellow flower'] },
      'flower',
      'bright',
      'summer',
      'garden classic',
    ],
  }),
  createEmoji({
    id: 'potted-sprout',
    emoji: '🪴',
    name: 'Potted Sprout',
    cost: 65,
    category: 'plants',
    popularity: 2,
    tags: ['sprout', 'potted plant', 'seedling', 'houseplant', 'clay pot'],
  }),
  createEmoji({
    id: 'hanging-ivy',
    emoji: '🌿',
    name: 'Hanging Ivy',
    cost: 60,
    category: 'plants',
    popularity: 3,
    tags: ['ivy', 'vines', 'greenery', 'trailing plant', 'foliage'],
  }),
  createEmoji({
    id: 'tulip-row',
    emoji: '🌷',
    name: 'Tulip Row',
    cost: 55,
    category: 'plants',
    popularity: 4,
    tags: ['tulip', 'spring flower', 'pink flower', 'garden bed'],
  }),
  createEmoji({
    id: 'wild-mushroom',
    emoji: '🍄',
    name: 'Wild Mushroom',
    cost: 70,
    category: 'plants',
    popularity: 5,
    tags: ['mushroom', 'toadstool', 'forest floor', 'fungi', 'whimsy'],
  }),
  createEmoji({
    id: 'fruit-grove',
    emoji: '🍎',
    name: 'Fruit Grove',
    cost: 68,
    category: 'plants',
    popularity: 6,
    tags: ['apple tree', 'orchard', 'fruit', 'autumn harvest'],
  }),
  createEmoji({
    id: 'desert-cactus',
    emoji: '🌵',
    name: 'Desert Cactus',
    cost: 72,
    category: 'plants',
    popularity: 7,
    tags: ['cactus', 'succulent', 'desert', 'arid garden', 'spines'],
  }),
  createEmoji({
    id: 'evergreen-pine',
    emoji: '🌲',
    name: 'Evergreen Pine',
    cost: 82,
    category: 'plants',
    popularity: 8,
    tags: ['pine', 'evergreen', 'forest tree', 'winter', 'woodland'],
  }),
  createEmoji({
    id: 'golden-sunrise',
    emoji: '🌅',
    name: 'Golden Sunrise',
    cost: 112,
    category: 'scenery',
    popularity: 9,
    tags: ['sunrise', 'morning sky', 'sunrise horizon', 'warm light'],
  }),
  createEmoji({
    id: 'midday-sun',
    emoji: '🌞',
    name: 'Midday Sun',
    cost: 124,
    category: 'scenery',
    popularity: 10,
    tags: ['sun', 'sunlight', 'bright sky', 'daytime', 'solar'],
  }),
  createEmoji({
    id: 'rainbow-arc',
    emoji: '🌈',
    name: 'Rainbow Arc',
    cost: 135,
    category: 'scenery',
    popularity: 11,
    tags: ['rainbow', 'colorful sky', 'after rain', 'magic light'],
  }),
  createEmoji({
    id: 'soft-clouds',
    emoji: '🌤️',
    name: 'Soft Clouds',
    cost: 104,
    category: 'scenery',
    popularity: 12,
    tags: ['clouds', 'partly sunny', 'breeze', 'gentle weather'],
  }),
  createEmoji({
    id: 'twilight-moon',
    emoji: '🌙',
    name: 'Twilight Moon',
    cost: 130,
    category: 'scenery',
    popularity: 13,
    tags: ['moon', 'night sky', 'evening', 'calm', 'glow'],
  }),
  createEmoji({
    id: 'shooting-star-trail',
    emoji: '🌠',
    name: 'Shooting Star Trail',
    cost: 142,
    category: 'scenery',
    popularity: 14,
    tags: ['shooting star', 'wish', 'night sparkle', 'meteor'],
  }),
  createEmoji({
    id: 'spring-rain',
    emoji: '🌧️',
    name: 'Spring Rain',
    cost: 110,
    category: 'scenery',
    popularity: 15,
    tags: ['rain', 'shower', 'storm', 'water', 'refresh'],
  }),
  createEmoji({
    id: 'garden-firefly',
    emoji: '🪄',
    name: 'Garden Firefly Glow',
    cost: 108,
    category: 'accents',
    popularity: 16,
    tags: ['firefly', 'sparkle', 'wand light', 'magic glow', 'tiny lights'],
  }),
  createEmoji({
    id: 'honeybee-buzz',
    emoji: '🐝',
    name: 'Honeybee Buzz',
    cost: 78,
    category: 'creatures',
    popularity: 17,
    tags: ['bee', 'pollinator', 'buzz', 'striped insect', 'honey'],
  }),
  createEmoji({
    id: 'monarch-butterfly',
    emoji: '🦋',
    name: 'Monarch Butterfly',
    cost: 82,
    category: 'creatures',
    popularity: 18,
    tags: ['butterfly', 'wings', 'flutter', 'orange butterfly', 'pollinator'],
  }),
  createEmoji({
    id: 'ladybug-luck',
    emoji: '🐞',
    name: 'Ladybug Luck',
    cost: 76,
    category: 'creatures',
    popularity: 19,
    tags: ['ladybug', 'ladybird', 'spots', 'garden insect'],
  }),
  createEmoji({
    id: 'songbird-perch',
    emoji: '🐦',
    name: 'Songbird Perch',
    cost: 84,
    category: 'creatures',
    popularity: 20,
    tags: ['bird', 'songbird', 'perched bird', 'tweet'],
  }),
  createEmoji({
    id: 'field-bunny',
    emoji: '🐇',
    name: 'Field Bunny',
    cost: 88,
    category: 'creatures',
    popularity: 21,
    tags: ['bunny', 'rabbit', 'hare', 'spring critter'],
  }),
  createEmoji({
    id: 'garden-tortoise',
    emoji: '🐢',
    name: 'Garden Tortoise',
    cost: 86,
    category: 'creatures',
    popularity: 22,
    tags: ['turtle', 'tortoise', 'slow friend', 'shell'],
  }),
  createEmoji({
    id: 'curious-cat',
    emoji: '🐈',
    name: 'Curious Garden Cat',
    cost: 94,
    category: 'creatures',
    popularity: 23,
    tags: ['cat', 'kitty', 'pet', 'feline', 'garden companion'],
  }),
  createEmoji({
    id: 'cozy-picnic',
    emoji: '🧺',
    name: 'Cozy Picnic Basket',
    cost: 98,
    category: 'features',
    popularity: 24,
    tags: ['picnic', 'basket', 'blanket', 'snacks', 'outing'],
  }),
  createEmoji({
    id: 'garden-lantern',
    emoji: '🏮',
    name: 'Garden Lantern',
    cost: 96,
    category: 'features',
    popularity: 25,
    tags: ['lantern', 'hanging light', 'glow', 'evening lighting'],
  }),
  createEmoji({
    id: 'stone-path',
    emoji: '🧱',
    name: 'Brick Garden Path',
    cost: 90,
    category: 'features',
    popularity: 26,
    tags: ['brick path', 'garden walkway', 'stonework', 'pathway', 'patterned steps'],
  }),
  createEmoji({
    id: 'garden-fountain',
    emoji: '⛲',
    name: 'Garden Fountain',
    cost: 148,
    category: 'features',
    popularity: 27,
    tags: ['fountain', 'water feature', 'splash', 'centerpiece'],
  }),
  createEmoji({
    id: 'greenhouse-nook',
    emoji: '🏡',
    name: 'Greenhouse Nook',
    cost: 185,
    category: 'features',
    popularity: 28,
    tags: ['greenhouse', 'garden home', 'glass house', 'cozy corner'],
  }),
  createEmoji({
    id: 'wooden-bench',
    emoji: '🪑',
    name: 'Wooden Garden Bench',
    cost: 132,
    category: 'features',
    popularity: 29,
    tags: ['bench', 'seat', 'rest spot', 'gather'],
  }),
  createEmoji({
    id: 'herbal-bouquet',
    emoji: '💐',
    name: 'Herbal Bouquet',
    cost: 102,
    category: 'accents',
    popularity: 30,
    tags: ['bouquet', 'flowers', 'arrangement', 'celebration'],
  }),
  createEmoji({
    id: 'glittering-lights',
    emoji: '✨',
    name: 'Glittering Lights',
    cost: 114,
    category: 'accents',
    popularity: 31,
    tags: ['sparkle', 'twinkle', 'stars', 'fairy lights'],
  }),
  createEmoji({
    id: 'garden-heart',
    emoji: '💚',
    name: 'Garden Heart Glow',
    cost: 110,
    category: 'accents',
    popularity: 32,
    tags: ['heart', 'green heart', 'love', 'care'],
  }),
  createEmoji({
    id: 'campfire-cozy',
    emoji: '🔥',
    name: 'Campfire Cozy',
    cost: 152,
    category: 'features',
    popularity: 33,
    tags: ['fire', 'campfire', 'warmth', 'gather'],
  }),
  createEmoji({
    id: 'dawn-dew',
    emoji: '💧',
    name: 'Dawn Dew Drop',
    cost: 99,
    category: 'accents',
    popularity: 34,
    tags: ['water drop', 'dew', 'refreshing', 'morning'],
  }),
  createEmoji({
    id: 'garden-rainbow-flower',
    emoji: '🌼',
    name: 'Garden Daisy',
    cost: 90,
    category: 'plants',
    popularity: 35,
    tags: ['daisy', 'wildflower', 'yellow bloom', 'sunny'],
  }),
  createEmoji({
    id: 'wind-swirls',
    emoji: '💨',
    name: 'Whistling Wind Swirls',
    cost: 104,
    category: 'accents',
    popularity: 36,
    tags: ['wind', 'gust', 'breeze', 'movement'],
  }),
  createEmoji({
    id: 'glowing-star',
    emoji: '🌟',
    name: 'Glowing Star',
    cost: 128,
    category: 'accents',
    popularity: 37,
    tags: ['star', 'shine', 'highlight', 'night sparkle'],
  }),
  createEmoji({
    id: 'tiny-sprouts',
    emoji: '🌱',
    name: 'Tiny Sprouts',
    cost: 82,
    category: 'plants',
    popularity: 38,
    tags: ['sprout', 'seedling', 'new growth', 'fresh'],
  }),
  createEmoji({
    id: 'lily-pad-pond',
    emoji: '🪷',
    name: 'Lily Pad Pond',
    cost: 150,
    category: 'features',
    popularity: 39,
    tags: ['lotus', 'pond', 'water garden', 'tranquil'],
  }),
  createEmoji({
    id: 'lavender-lane',
    emoji: '🪻',
    name: 'Lavender Lane',
    category: 'plants',
    popularity: 40,
    tags: ['lavender', 'purple flowers', 'fragrance', 'calming bloom', 'herbal'],
  }),
  createEmoji({
    id: 'bonsai-retreat',
    emoji: '🎍',
    name: 'Bonsai Retreat',
    category: 'plants',
    popularity: 41,
    tags: ['bonsai', 'mini tree', 'zen garden', 'trimmed branches', 'careful pruning'],
  }),
  createEmoji({
    id: 'autumn-maple-grove',
    emoji: '🍁',
    name: 'Maple Leaf',
    category: 'scenery',
    popularity: 42,
    tags: ['maple', 'fall leaves', 'crimson canopy', 'seasonal color', 'foliage'],
  }),
  createEmoji({
    id: 'morning-mist-drift',
    emoji: '🌫️',
    name: 'Morning Mist Drift',
    category: 'scenery',
    popularity: 43,
    tags: ['mist', 'fog', 'soft haze', 'cool dawn', 'breeze'],
  }),
  createEmoji({
    id: 'gentle-hedgehog',
    emoji: '🦔',
    name: 'Gentle Hedgehog',
    category: 'creatures',
    popularity: 44,
    tags: ['hedgehog', 'garden friend', 'spines', 'nocturnal', 'critter'],
  }),
  createEmoji({
    id: 'midnight-owl-roost',
    emoji: '🦉',
    name: 'Midnight Owl Roost',
    category: 'creatures',
    popularity: 45,
    tags: ['owl', 'night watch', 'wisdom', 'perch', 'stars'],
  }),
  createEmoji({
    id: 'sage-teahouse',
    emoji: '🍵',
    name: 'Sage Teahouse',
    category: 'features',
    popularity: 46,
    tags: ['tea', 'tea house', 'calm retreat', 'warm cup', 'gather'],
  }),
  createEmoji({
    id: 'stone-arch-bridge',
    emoji: '🌉',
    name: 'Stone Arch Bridge',
    category: 'features',
    popularity: 47,
    tags: ['bridge', 'archway', 'garden path', 'walkover', 'water crossing'],
  }),
  createEmoji({
    id: 'twilight-wind-chimes',
    emoji: '🎐',
    name: 'Twilight Wind Chimes',
    category: 'accents',
    popularity: 48,
    tags: ['wind chime', 'gentle sound', 'breeze song', 'evening accent', 'hanging charm'],
  }),
  createEmoji({
    id: 'glimmer-orb-lights',
    emoji: '🔮',
    name: 'Glimmer Orb Lights',
    category: 'accents',
    popularity: 49,
    tags: ['orb', 'mystic glow', 'path lights', 'floating light', 'spark'],
  }),
  createEmoji({
    id: 'pocket-crickets',
    emoji: '🦗',
    name: 'Pocket Crickets',
    category: 'creatures',
    popularity: 50,
    tags: ['cricket', 'evening song', 'chirp', 'nighttime', 'garden sound'],
  }),
  createEmoji({
    id: 'cobblestone-gate',
    emoji: '🚪',
    name: 'Cobblestone Gate',
    category: 'features',
    popularity: 51,
    tags: ['garden gate', 'entryway', 'stonework', 'welcome arch', 'entrance'],
  }),
  createEmoji({
    id: 'evergreen-oak',
    emoji: '🌳',
    name: 'Evergreen Oak',
    category: 'plants',
    popularity: 52,
    tags: ['oak tree', 'canopy shade', 'stately tree', 'garden landmark', 'evergreen'],
  }),
  createEmoji({
    id: 'rose-archway',
    emoji: '🌹',
    name: 'Rose Archway',
    category: 'plants',
    popularity: 53,
    tags: ['rose arch', 'climbing roses', 'garden entrance', 'petals', 'romantic walkway'],
  }),
  createEmoji({
    id: 'sakura-breeze',
    emoji: '🌸',
    name: 'Sakura Breeze',
    category: 'plants',
    popularity: 54,
    tags: ['cherry blossom', 'sakura', 'pink petals', 'spring bloom', 'hanami'],
  }),
  createEmoji({
    id: 'hibiscus-halo',
    emoji: '🌺',
    name: 'Hibiscus Halo',
    category: 'plants',
    popularity: 55,
    tags: ['hibiscus', 'tropical bloom', 'bold petals', 'vibrant flower', 'island garden'],
  }),
  createEmoji({
    id: 'strawberry-patch',
    emoji: '🍓',
    name: 'Strawberry Patch',
    category: 'plants',
    popularity: 56,
    tags: ['strawberry', 'berry patch', 'sweet harvest', 'garden fruit', 'red berries'],
  }),
  createEmoji({
    id: 'melon-vine',
    emoji: '🍈',
    name: 'Melon Vine',
    category: 'plants',
    popularity: 57,
    tags: ['melon', 'creeping vine', 'green melon', 'summer harvest', 'garden fruit'],
  }),
  createEmoji({
    id: 'blueberry-bramble',
    emoji: '🫐',
    name: 'Blueberry Bramble',
    category: 'plants',
    popularity: 58,
    tags: ['blueberry', 'wild berry', 'purple fruit', 'garden bush', 'sweet harvest'],
  }),
  createEmoji({
    id: 'swan-lagoon',
    emoji: '🦢',
    name: 'Swan Lagoon',
    category: 'creatures',
    popularity: 59,
    tags: ['swan', 'calm water', 'graceful bird', 'lagoon', 'pond life'],
  }),
  createEmoji({
    id: 'peacock-parade',
    emoji: '🦚',
    name: 'Peacock Parade',
    category: 'creatures',
    popularity: 60,
    tags: ['peacock', 'feather fan', 'vibrant bird', 'garden parade', 'plumage'],
  }),
  createEmoji({
    id: 'garden-flamingo',
    emoji: '🦩',
    name: 'Garden Flamingo',
    category: 'creatures',
    popularity: 61,
    tags: ['flamingo', 'garden bird', 'pink bird', 'lawn art', 'tropical wader'],
  }),
  createEmoji({
    id: 'foxtail-hollow',
    emoji: '🦊',
    name: 'Foxtail Hollow',
    category: 'creatures',
    popularity: 62,
    tags: ['fox', 'forest friend', 'clever critter', 'bushy tail', 'garden visitor'],
  }),
  createEmoji({
    id: 'river-otter',
    emoji: '🦦',
    name: 'River Otter',
    category: 'creatures',
    popularity: 63,
    tags: ['otter', 'riverbank', 'playful swimmer', 'freshwater friend', 'whiskers'],
  }),
  createEmoji({
    id: 'winged-companion',
    emoji: '🪽',
    name: 'Winged Companion',
    category: 'accents',
    popularity: 64,
    tags: ['wing', 'feather', 'flutter', 'airborne', 'light breeze'],
  }),
  createEmoji({
    id: 'lantern-glow',
    emoji: '🪔',
    name: 'Lantern Glow Diya',
    category: 'accents',
    popularity: 65,
    tags: ['oil lamp', 'festival glow', 'warm flame', 'evening light', 'diya lantern'],
  }),
  createEmoji({
    id: 'picnic-basket',
    emoji: '🥪',
    name: 'Picnic Sandwich Stack',
    category: 'features',
    popularity: 66,
    tags: ['sandwich', 'packed lunch', 'picnic basket', 'layered bites', 'outdoor meal'],
  }),
  createEmoji({
    id: 'watering-pail',
    emoji: '🪣',
    name: 'Watering Pail',
    category: 'features',
    popularity: 67,
    tags: ['watering can', 'garden tool', 'sprinkle', 'metal pail', 'garden care'],
  }),
  createEmoji({
    id: 'mossy-log',
    emoji: '🪵',
    name: 'Mossy Log',
    category: 'features',
    popularity: 68,
    tags: ['mossy log', 'forest floor', 'wooden log', 'soft moss', 'natural seat'],
  }),
  createEmoji({
    id: 'riverstone-stack',
    emoji: '🪨',
    name: 'Riverstone Stack',
    category: 'features',
    popularity: 69,
    tags: ['river stone', 'zen rocks', 'stacked stones', 'garden cairn', 'smooth pebbles'],
  }),
  createEmoji({
    id: 'empty-nest-perch',
    emoji: '🪹',
    name: 'Empty Nest Perch',
    category: 'features',
    popularity: 70,
    tags: ['empty nest', 'twigs', 'perch', 'tree branch', 'quiet rest'],
  }),
  createEmoji({
    id: 'cozy-nest-eggs',
    emoji: '🪺',
    name: 'Cozy Nest Eggs',
    category: 'features',
    popularity: 71,
    tags: ['nest eggs', 'blue eggs', 'twig nest', 'springtime', 'gentle care'],
  }),
  createEmoji({
    id: 'ginger-root-bundle',
    emoji: '🫚',
    name: 'Ginger Root Bundle',
    category: 'plants',
    popularity: 72,
    tags: ['ginger root', 'spice', 'warmth', 'herbal', 'market bundle'],
  }),
  createEmoji({
    id: 'garden-pea-pod',
    emoji: '🫛',
    name: 'Garden Pea Pod',
    category: 'plants',
    popularity: 73,
    tags: ['pea pod', 'peas', 'fresh greens', 'snap pea', 'climbing vine'],
  }),
  createEmoji({
    id: 'garlic-bulb-cluster',
    emoji: '🧄',
    name: 'Garlic Bulb Cluster',
    category: 'plants',
    popularity: 74,
    tags: ['garlic bulb', 'kitchen garden', 'aroma', 'culinary', 'clove bundle'],
  }),
  createEmoji({
    id: 'stone-flatbread-platter',
    emoji: '🫓',
    name: 'Stone Flatbread Platter',
    category: 'features',
    popularity: 75,
    tags: ['flatbread', 'warm loaf', 'hearth', 'artisan bake', 'shared snack'],
  }),
  createEmoji({
    id: 'fireside-fondue',
    emoji: '🫕',
    name: 'Fireside Fondue',
    category: 'features',
    popularity: 76,
    tags: ['fondue pot', 'cozy treat', 'evening glow', 'shared bites', 'golden cheese'],
  }),
  createEmoji({
    id: 'sunlit-preserve-jar',
    emoji: '🫙',
    name: 'Sunlit Preserve Jar',
    category: 'features',
    popularity: 77,
    tags: ['glass jar', 'homemade jam', 'summer fruit', 'pantry shelf', 'sweet spread'],
  }),
  createEmoji({
    id: 'meadow-cupcake-stand',
    emoji: '🧁',
    name: 'Meadow Cupcake Stand',
    category: 'accents',
    popularity: 78,
    tags: ['cupcake', 'pastel frosting', 'garden party', 'sweet treat', 'dessert stand'],
  }),
  createEmoji({
    id: 'cookie-platter',
    emoji: '🍪',
    name: 'Cookie Platter',
    category: 'accents',
    popularity: 79,
    tags: ['cookie', 'fresh baked', 'comfort snack', 'chocolate chip', 'afternoon tea'],
  }),
  createEmoji({
    id: 'harvest-hand-pie',
    emoji: '🥧',
    name: 'Harvest Hand Pie',
    category: 'accents',
    popularity: 80,
    tags: ['pie', 'autumn dessert', 'cinnamon spice', 'homestead treat', 'golden crust'],
  }),
  createEmoji({
    id: 'sparkling-juice-carton',
    emoji: '🧃',
    name: 'Sparkling Juice Carton',
    category: 'accents',
    popularity: 81,
    tags: ['juice box', 'refreshing sip', 'fruit drink', 'picnic cooler', 'hydration'],
  }),
  createEmoji({
    id: 'frosted-ice-gems',
    emoji: '🧊',
    name: 'Frosted Ice Gems',
    category: 'accents',
    popularity: 82,
    tags: ['ice cube', 'cool breeze', 'frost sparkle', 'chill station', 'glass clink'],
  }),
  createEmoji({
    id: 'bubble-tea-cart',
    emoji: '🧋',
    name: 'Bubble Tea Cart',
    category: 'features',
    popularity: 83,
    tags: ['bubble tea', 'tapioca pearls', 'tea stand', 'garden cafe', 'sweet sip'],
  }),
  createEmoji({
    id: 'mate-garden-gourd',
    emoji: '🧉',
    name: 'Mate Garden Gourd',
    category: 'features',
    popularity: 84,
    tags: ['mate gourd', 'shared drink', 'herbal infusion', 'cozy gathering', 'metal straw'],
  }),
  createEmoji({
    id: 'sky-dancing-kite',
    emoji: '🪁',
    name: 'Sky Dancing Kite',
    category: 'scenery',
    popularity: 85,
    tags: ['kite', 'breezy day', 'string trail', 'playful sky', 'spring outing'],
  }),
  createEmoji({
    id: 'garden-lounge-sofa',
    emoji: '🛋️',
    name: 'Garden Lounge Sofa',
    category: 'features',
    popularity: 86,
    tags: ['sofa', 'outdoor lounge', 'cushions', 'relax corner', 'sunset seating'],
  }),
  createEmoji({
    id: 'playful-park-slide',
    emoji: '🛝',
    name: 'Playful Park Slide',
    category: 'features',
    popularity: 87,
    tags: ['slide', 'playground', 'family fun', 'park feature', 'joyful swoop'],
  }),
  createEmoji({
    id: 'lucky-garden-coin',
    emoji: '🪙',
    name: 'Lucky Garden Coin',
    category: 'accents',
    popularity: 88,
    tags: ['coin', 'lucky charm', 'gleaming gold', 'wish token', 'hidden treasure'],
  }),
  createEmoji({
    id: 'nazar-sun-catcher',
    emoji: '🧿',
    name: 'Nazar Sun Catcher',
    category: 'accents',
    popularity: 89,
    tags: ['nazar charm', 'protective talisman', 'window glimmer', 'blue glass', 'sun catcher'],
  }),
  createEmoji({
    id: 'tidepool-coral-cluster',
    emoji: '🪸',
    name: 'Tidepool Coral Cluster',
    category: 'scenery',
    popularity: 91,
    tags: ['coral', 'tidepool', 'marine garden', 'coastal color', 'undersea life'],
  }),
  createEmoji({
    id: 'story-nesting-dolls',
    emoji: '🪆',
    name: 'Story Nesting Dolls',
    category: 'accents',
    popularity: 92,
    tags: ['nesting dolls', 'painted keepsake', 'folk art', 'layered surprise', 'display shelf'],
  }),
  createEmoji({
    id: 'citrus-sunburst-grove',
    emoji: '🍊',
    name: 'Citrus Sunburst Grove',
    category: 'plants',
    popularity: 93,
    tags: ['orange grove', 'citrus', 'sunny fruit', 'scented blossom', 'bright canopy'],
  }),
  createEmoji({
    id: 'lemontwist-orchard',
    emoji: '🍋',
    name: 'Lemontwist Orchard',
    category: 'plants',
    popularity: 94,
    tags: ['lemon tree', 'zesty fruit', 'citrus grove', 'yellow bloom', 'fresh zest'],
  }),
  createEmoji({
    id: 'vineyard-trellis-cluster',
    emoji: '🍇',
    name: 'Vineyard Trellis Cluster',
    category: 'plants',
    popularity: 95,
    tags: ['grapes', 'vineyard', 'trellis vines', 'clustered fruit', 'late harvest'],
  }),
  createEmoji({
    id: 'river-melon-patch',
    emoji: '🍉',
    name: 'River Melon Patch',
    category: 'plants',
    popularity: 96,
    tags: ['watermelon', 'summer fruit', 'striped rind', 'picnic harvest', 'juicy patch'],
  }),
  createEmoji({
    id: 'scarlet-cherry-twins',
    emoji: '🍒',
    name: 'Scarlet Cherry Twins',
    category: 'plants',
    popularity: 97,
    tags: ['cherries', 'pair of fruit', 'sweet orchard', 'blossom stem', 'juicy duo'],
  }),
  createEmoji({
    id: 'velvet-peach-canopy',
    emoji: '🍑',
    name: 'Velvet Peach Canopy',
    category: 'plants',
    popularity: 98,
    tags: ['peach', 'summer orchard', 'fuzzy fruit', 'blush petals', 'sunset grove'],
  }),
  createEmoji({
    id: 'pineapple-lantern-ridge',
    emoji: '🍍',
    name: 'Pineapple Lantern Ridge',
    category: 'plants',
    popularity: 99,
    tags: ['pineapple', 'tropical fruit', 'spiky crown', 'golden harvest', 'sunny slope'],
  }),
  createEmoji({
    id: 'island-coconut-canopy',
    emoji: '🥥',
    name: 'Island Coconut Canopy',
    category: 'plants',
    popularity: 100,
    tags: ['coconut', 'palm cluster', 'tropical shade', 'shell husk', 'island breeze'],
  }),
  createEmoji({
    id: 'kiwi-trellis-drift',
    emoji: '🥝',
    name: 'Kiwi Trellis Drift',
    category: 'plants',
    popularity: 101,
    tags: ['kiwi', 'vine fruit', 'emerald slices', 'garden pergola', 'tartan rind'],
  }),
  createEmoji({
    id: 'mango-gold-grove',
    emoji: '🥭',
    name: 'Mango Gold Grove',
    category: 'plants',
    popularity: 102,
    tags: ['mango', 'tropical orchard', 'sunny fruit', 'sweet nectar', 'golden branch'],
  }),
  createEmoji({
    id: 'heritage-tomato-vine',
    emoji: '🍅',
    name: 'Heritage Tomato Vine',
    category: 'plants',
    popularity: 103,
    tags: ['tomato', 'garden patch', 'vine ripened', 'ruby fruit', 'heirloom produce'],
  }),
  createEmoji({
    id: 'midnight-eggplant-row',
    emoji: '🍆',
    name: 'Midnight Eggplant Row',
    category: 'plants',
    popularity: 104,
    tags: ['eggplant', 'nightshade', 'deep purple', 'row planting', 'gleaming skin'],
  }),
  createEmoji({
    id: 'broccoli-forest-floret',
    emoji: '🥦',
    name: 'Broccoli Forest Floret',
    category: 'plants',
    popularity: 105,
    tags: ['broccoli', 'floret cluster', 'crunchy green', 'veggie patch', 'garden harvest'],
  }),
  createEmoji({
    id: 'cool-cucumber-tangle',
    emoji: '🥒',
    name: 'Cool Cucumber Tangle',
    category: 'plants',
    popularity: 106,
    tags: ['cucumber', 'vine', 'refreshing crunch', 'garden trellis', 'emerald spiral'],
  }),
  createEmoji({
    id: 'cornfield-sunrise-stalks',
    emoji: '🌽',
    name: 'Cornfield Sunrise Stalks',
    category: 'plants',
    popularity: 107,
    tags: ['corn', 'maize', 'tall stalks', 'golden tassel', 'farm row'],
  }),
  createEmoji({
    id: 'carrot-top-bundle',
    emoji: '🥕',
    name: 'Carrot Top Bundle',
    category: 'plants',
    popularity: 108,
    tags: ['carrot', 'root vegetable', 'orange harvest', 'garden bed', 'crisp crunch'],
  }),
  createEmoji({
    id: 'amber-sweet-potato-hill',
    emoji: '🍠',
    name: 'Amber Sweet Potato Hill',
    category: 'plants',
    popularity: 109,
    tags: ['sweet potato', 'root patch', 'baked aroma', 'autumn plot', 'earthy harvest'],
  }),
  createEmoji({
    id: 'starlit-bean-vines',
    emoji: '🫘',
    name: 'Starlit Bean Vines',
    category: 'plants',
    popularity: 110,
    tags: ['beans', 'climbing vine', 'night bloom', 'protein pods', 'garden lattice'],
  }),
  createEmoji({
    id: 'mountain-dawn-crest',
    emoji: '🌄',
    name: 'Mountain Dawn Crest',
    category: 'scenery',
    popularity: 111,
    tags: ['sunrise', 'mountain range', 'orange horizon', 'travel view', 'alpine glow'],
  }),
  createEmoji({
    id: 'sunset-ridge-horizon',
    emoji: '🌇',
    name: 'Sunset Ridge Horizon',
    category: 'scenery',
    popularity: 112,
    tags: ['sunset', 'city silhouette', 'glowing skyline', 'evening light', 'twilight sky'],
  }),
  createEmoji({
    id: 'twilight-metro-aurora',
    emoji: '🌆',
    name: 'Twilight Metro Aurora',
    category: 'scenery',
    popularity: 113,
    tags: ['cityscape', 'violet dusk', 'windows aglow', 'urban evening', 'skyline'],
  }),
  createEmoji({
    id: 'starlit-promenade',
    emoji: '🌃',
    name: 'Starlit Promenade',
    category: 'scenery',
    popularity: 114,
    tags: ['night city', 'stars', 'evening walk', 'glittering lights', 'urban sky'],
  }),
  createEmoji({
    id: 'galaxy-overlook',
    emoji: '🌌',
    name: 'Galaxy Overlook',
    category: 'scenery',
    popularity: 115,
    tags: ['milky way', 'night sky', 'cosmic swirl', 'stargazing', 'midnight view'],
  }),
  createEmoji({
    id: 'ember-volcano-crest',
    emoji: '🌋',
    name: 'Ember Volcano Crest',
    category: 'scenery',
    popularity: 116,
    tags: ['volcano', 'lava glow', 'smoke plume', 'island peak', 'fiery mountain'],
  }),
  createEmoji({
    id: 'snowcap-summit-trail',
    emoji: '🏔️',
    name: 'Snowcap Summit Trail',
    category: 'scenery',
    popularity: 117,
    tags: ['mountain', 'snow peak', 'alpine trail', 'crisp air', 'hiking path'],
  }),
  createEmoji({
    id: 'wanderer-campfire-cove',
    emoji: '🏕️',
    name: 'Wanderer Campfire Cove',
    category: 'scenery',
    popularity: 118,
    tags: ['campground', 'tent', 'stars above', 'night retreat', 'bonfire glow'],
  }),
  createEmoji({
    id: 'parasol-shoreline',
    emoji: '🏖️',
    name: 'Parasol Shoreline',
    category: 'scenery',
    popularity: 119,
    tags: ['beach', 'umbrella', 'coastal sand', 'waves', 'holiday rest'],
  }),
  createEmoji({
    id: 'lagoon-island-haven',
    emoji: '🏝️',
    name: 'Lagoon Island Haven',
    category: 'scenery',
    popularity: 120,
    tags: ['island', 'tropical', 'solitude', 'palm beach', 'turquoise water'],
  }),
  createEmoji({
    id: 'pondside-frog-chorus',
    emoji: '🐸',
    name: 'Pondside Frog Chorus',
    category: 'creatures',
    popularity: 121,
    tags: ['frog', 'lily pad singer', 'rainy day', 'croak melody', 'pond friend'],
  }),
  createEmoji({
    id: 'mossy-snail-trail',
    emoji: '🐌',
    name: 'Mossy Snail Trail',
    category: 'creatures',
    popularity: 122,
    tags: ['snail', 'slow wanderer', 'spiral shell', 'morning dew', 'garden crawler'],
  }),
  createEmoji({
    id: 'acorn-chipmunk-dash',
    emoji: '🐿️',
    name: 'Acorn Chipmunk Dash',
    category: 'creatures',
    popularity: 123,
    tags: ['chipmunk', 'acorn gatherer', 'striped tail', 'burrow friend', 'quick scurry'],
  }),
  createEmoji({
    id: 'garden-reef-octopus',
    emoji: '🐙',
    name: 'Garden Reef Octopus',
    category: 'creatures',
    popularity: 124,
    tags: ['octopus', 'tidal pool', 'shifting colors', 'curious tentacles', 'ocean visitor'],
  }),
  createEmoji({
    id: 'koi-glassfish',
    emoji: '🐠',
    name: 'Koi Glassfish',
    category: 'creatures',
    popularity: 125,
    tags: ['fish', 'koi pond', 'glimmer scales', 'tranquil swim', 'water companion'],
  }),
  createEmoji({
    id: 'puffer-lagoon-guest',
    emoji: '🐡',
    name: 'Puffer Lagoon Guest',
    category: 'creatures',
    popularity: 126,
    tags: ['pufferfish', 'puffball fish', 'coastal reef', 'playful float', 'spiny friend'],
  }),
  createEmoji({
    id: 'sunrise-dolphin-leap',
    emoji: '🐬',
    name: 'Sunrise Dolphin Leap',
    category: 'creatures',
    popularity: 127,
    tags: ['dolphin', 'ocean jump', 'wave arc', 'friendly marine', 'sparkling spray'],
  }),
  createEmoji({
    id: 'whale-song-drift',
    emoji: '🐳',
    name: 'Whale Song Drift',
    category: 'creatures',
    popularity: 128,
    tags: ['whale', 'deep sea', 'gentle giant', 'ocean current', 'soothing call'],
  }),
  createEmoji({
    id: 'reef-shark-glide',
    emoji: '🦈',
    name: 'Reef Shark Glide',
    category: 'creatures',
    popularity: 129,
    tags: ['shark', 'sleek fin', 'blue water', 'coastal guardian', 'swift swim'],
  }),
  createEmoji({
    id: 'harbor-lobster-nook',
    emoji: '🦞',
    name: 'Harbor Lobster Nook',
    category: 'creatures',
    popularity: 130,
    tags: ['lobster', 'tidal catch', 'rocky inlet', 'seafood dock', 'crimson shell'],
  }),
  createEmoji({
    id: 'lagoon-canoe-launch',
    emoji: '🛶',
    name: 'Lagoon Canoe Launch',
    category: 'features',
    popularity: 131,
    tags: ['canoe', 'dock', 'paddle adventure', 'lake outing', 'wood pier'],
  }),
  createEmoji({
    id: 'palm-hut-hideaway',
    emoji: '🛖',
    name: 'Palm Hut Hideaway',
    category: 'features',
    popularity: 132,
    tags: ['hut', 'thatch roof', 'tropical rest', 'shaded shelter', 'breeze break'],
  }),
  createEmoji({
    id: 'garden-shrine-pavilion',
    emoji: '🛕',
    name: 'Garden Shrine Pavilion',
    category: 'features',
    popularity: 133,
    tags: ['temple', 'meditation', 'ornate arch', 'quiet refuge', 'lantern glow'],
  }),
  createEmoji({
    id: 'greenhouse-window-arch',
    emoji: '🪟',
    name: 'Greenhouse Window Arch',
    category: 'features',
    popularity: 134,
    tags: ['glass window', 'sunlight beam', 'plant house', 'framed view', 'paned arch'],
  }),
  createEmoji({
    id: 'reflective-garden-mirror',
    emoji: '🪞',
    name: 'Reflective Garden Mirror',
    category: 'features',
    popularity: 135,
    tags: ['mirror', 'shimmer frame', 'light bounce', 'illusion depth', 'ornament'],
  }),
  createEmoji({
    id: 'outdoor-soaking-tub',
    emoji: '🛁',
    name: 'Outdoor Soaking Tub',
    category: 'features',
    popularity: 136,
    tags: ['bathtub', 'spa retreat', 'steam soak', 'garden bath', 'relax station'],
  }),
  createEmoji({
    id: 'sparkler-sky-burst',
    emoji: '🎇',
    name: 'Sparkler Sky Burst',
    category: 'accents',
    popularity: 137,
    tags: ['sparkler', 'festive light', 'night sparkle', 'celebration flare', 'glitter arcs'],
  }),
  createEmoji({
    id: 'firework-bloom-finale',
    emoji: '🎆',
    name: 'Firework Bloom Finale',
    category: 'accents',
    popularity: 138,
    tags: ['fireworks', 'festival sky', 'bright bloom', 'night show', 'celebration'],
  }),
  createEmoji({
    id: 'ribbon-balloon-cluster',
    emoji: '🎈',
    name: 'Ribbon Balloon Cluster',
    category: 'accents',
    popularity: 139,
    tags: ['balloon', 'party float', 'color pop', 'garden gala', 'festive accent'],
  }),
  createEmoji({
    id: 'confetti-cannon-spritz',
    emoji: '🎉',
    name: 'Confetti Cannon Spritz',
    category: 'accents',
    popularity: 140,
    tags: ['party popper', 'celebration confetti', 'bursting streamers', 'joyful cheer', 'festive sparkle'],
  }),
  createEmoji({
    id: 'lantern-candle-nook',
    emoji: '🕯️',
    name: 'Lantern Candle Nook',
    category: 'accents',
    popularity: 141,
    tags: ['candle', 'warm glow', 'evening ambiance', 'soft light', 'flicker flame'],
  }),
  createEmoji({
    id: 'idea-lantern-bulb',
    emoji: '💡',
    name: 'Idea Lantern Bulb',
    category: 'accents',
    popularity: 142,
    tags: ['lightbulb', 'bright idea', 'illumination', 'glowing accent', 'spark of light'],
  }),
  createEmoji({
    id: 'sunset-roadster-lineup',
    emoji: '🚗',
    name: 'Sunset Roadster Lineup',
    category: 'features',
    popularity: 143,
    tags: ['car', 'convertible', 'sunset cruise', 'chrome shine', 'garden showcase'],
  }),
  createEmoji({
    id: 'vintage-wagon-pull-in',
    emoji: '🚙',
    name: 'Vintage Wagon Pull-In',
    category: 'features',
    popularity: 144,
    tags: ['wagon', 'retro ride', 'weekend outing', 'family tour', 'retro charm'],
  }),
  createEmoji({
    id: 'garden-taxi-stand',
    emoji: '🚕',
    name: 'Garden Taxi Stand',
    category: 'features',
    popularity: 145,
    tags: ['taxi', 'city cab', 'pickup point', 'arrival lane', 'striped canopy'],
  }),
  createEmoji({
    id: 'parkway-patrol-watch',
    emoji: '🚓',
    name: 'Parkway Patrol Watch',
    category: 'features',
    popularity: 146,
    tags: ['police car', 'security detail', 'night patrol', 'beacon lights', 'safety escort'],
  }),
  createEmoji({
    id: 'rescue-ambulance-bay',
    emoji: '🚑',
    name: 'Rescue Ambulance Bay',
    category: 'features',
    popularity: 147,
    tags: ['ambulance', 'first aid', 'emergency ready', 'white stripe', 'lifeline'],
  }),
  createEmoji({
    id: 'firehouse-engine-post',
    emoji: '🚒',
    name: 'Firehouse Engine Post',
    category: 'features',
    popularity: 148,
    tags: ['fire engine', 'hydrant crew', 'scarlet truck', 'rescue route', 'sirens ready'],
  }),
  createEmoji({
    id: 'evening-shuttle-loop',
    emoji: '🚐',
    name: 'Evening Shuttle Loop',
    category: 'features',
    popularity: 149,
    tags: ['shuttle van', 'group tour', 'courtesy coach', 'arrival plaza', 'evening glow'],
  }),
  createEmoji({
    id: 'freight-drop-turnaround',
    emoji: '🚚',
    name: 'Freight Drop Turnaround',
    category: 'features',
    popularity: 150,
    tags: ['delivery truck', 'cargo bay', 'service lane', 'steel ramp', 'garden supply'],
  }),
  createEmoji({
    id: 'long-haul-rig-rest',
    emoji: '🚛',
    name: 'Long Haul Rig Rest',
    category: 'features',
    popularity: 151,
    tags: ['semi truck', 'rest stop', 'fuel plaza', 'cargo convoy', 'night headlights'],
  }),
  createEmoji({
    id: 'harvest-tractor-row',
    emoji: '🚜',
    name: 'Harvest Tractor Row',
    category: 'features',
    popularity: 152,
    tags: ['tractor', 'farm helper', 'fresh tilled', 'field groove', 'rural charm'],
  }),
  createEmoji({
    id: 'race-day-pit-lane',
    emoji: '🏎️',
    name: 'Race Day Pit Lane',
    category: 'features',
    popularity: 153,
    tags: ['racing car', 'pit crew', 'checkered flag', 'track ready', 'speedway flair'],
  }),
  createEmoji({
    id: 'rally-bike-corner',
    emoji: '🏍️',
    name: 'Rally Bike Corner',
    category: 'features',
    popularity: 154,
    tags: ['motorcycle', 'touring route', 'leaning turn', 'helmet gleam', 'road rally'],
  }),
  createEmoji({
    id: 'sunrise-scooter-run',
    emoji: '🛵',
    name: 'Sunrise Scooter Run',
    category: 'features',
    popularity: 155,
    tags: ['scooter', 'morning ride', 'café commute', 'city buzz', 'breezy lane'],
  }),
  createEmoji({
    id: 'cycle-share-hub',
    emoji: '🚲',
    name: 'Cycle Share Hub',
    category: 'features',
    popularity: 156,
    tags: ['bicycle', 'bike rack', 'pedal tour', 'eco travel', 'garden trail'],
  }),
  createEmoji({
    id: 'garden-rickshaw-ridge',
    emoji: '🛺',
    name: 'Garden Rickshaw Ridge',
    category: 'features',
    popularity: 157,
    tags: ['rickshaw', 'carriage ride', 'lantern tour', 'heritage lane', 'market melody'],
  }),
  createEmoji({
    id: 'skyline-monorail-glide',
    emoji: '🚝',
    name: 'Skyline Monorail Glide',
    category: 'features',
    popularity: 158,
    tags: ['monorail', 'elevated rail', 'sky bridge', 'panorama view', 'modern transit'],
  }),
  createEmoji({
    id: 'mountain-tram-platform',
    emoji: '🚞',
    name: 'Mountain Tram Platform',
    category: 'features',
    popularity: 159,
    tags: ['tram', 'ridge climb', 'vintage coach', 'alpine station', 'summit scene'],
  }),
  createEmoji({
    id: 'cable-car-lookout',
    emoji: '🚠',
    name: 'Cable Car Lookout',
    category: 'features',
    popularity: 160,
    tags: ['cable car', 'aerial view', 'suspended cabin', 'cliffside ride', 'skyline sweep'],
  }),
  createEmoji({
    id: 'gondola-summit-lift',
    emoji: '🚡',
    name: 'Gondola Summit Lift',
    category: 'features',
    popularity: 161,
    tags: ['gondola', 'peak tour', 'glacier glide', 'station perch', 'airy ascent'],
  }),
  createEmoji({
    id: 'pickup-truck-outpost',
    emoji: '🛻',
    name: 'Pickup Truck Outpost',
    category: 'features',
    popularity: 162,
    tags: ['pickup truck', 'tailgate camp', 'tool rack', 'trail supplies', 'weekend haul'],
  }),
  createEmoji({
    id: 'soccer-goal-kick',
    emoji: '⚽',
    name: 'Soccer Goal Kick',
    category: 'accents',
    popularity: 163,
    tags: ['soccer ball', 'garden pitch', 'team play', 'field sport', 'match day'],
  }),
  createEmoji({
    id: 'backboard-bounce-court',
    emoji: '🏀',
    name: 'Backboard Bounce Court',
    category: 'accents',
    popularity: 164,
    tags: ['basketball', 'hoop dreams', 'street court', 'orange rim', 'fast break'],
  }),
  createEmoji({
    id: 'gridiron-huddle-marker',
    emoji: '🏈',
    name: 'Gridiron Huddle Marker',
    category: 'accents',
    popularity: 165,
    tags: ['football', 'yard line', 'team huddle', 'goal post', 'game whistle'],
  }),
  createEmoji({
    id: 'bullpen-warmup-base',
    emoji: '⚾',
    name: 'Bullpen Warmup Base',
    category: 'accents',
    popularity: 166,
    tags: ['baseball', 'diamond dust', 'pitchers mound', 'home plate', 'foul line'],
  }),
  createEmoji({
    id: 'softball-sunrise-diamond',
    emoji: '🥎',
    name: 'Softball Sunrise Diamond',
    category: 'accents',
    popularity: 167,
    tags: ['softball', 'infield glow', 'league night', 'bat crack', 'bright laces'],
  }),
  createEmoji({
    id: 'twilight-tennis-service',
    emoji: '🎾',
    name: 'Twilight Tennis Service',
    category: 'accents',
    popularity: 168,
    tags: ['tennis ball', 'baseline rally', 'court stripes', 'match point', 'racket swing'],
  }),
  createEmoji({
    id: 'seaside-volley-set',
    emoji: '🏐',
    name: 'Seaside Volley Set',
    category: 'accents',
    popularity: 169,
    tags: ['volleyball', 'sand court', 'pepper drill', 'serve receive', 'sunny spike'],
  }),
  createEmoji({
    id: 'rugby-scrum-circle',
    emoji: '🏉',
    name: 'Rugby Scrum Circle',
    category: 'accents',
    popularity: 170,
    tags: ['rugby ball', 'scrum pack', 'touch line', 'stadium roar', 'team drive'],
  }),
  createEmoji({
    id: 'meadow-disc-flight',
    emoji: '🥏',
    name: 'Meadow Disc Flight',
    category: 'accents',
    popularity: 171,
    tags: ['flying disc', 'field toss', 'ultimate drift', 'hover arc', 'wind read'],
  }),
  createEmoji({
    id: 'goalie-net-guard',
    emoji: '🥅',
    name: 'Goalie Net Guard',
    category: 'accents',
    popularity: 172,
    tags: ['goal net', 'keeper stance', 'crease sweep', 'shootout', 'defense line'],
  }),
  createEmoji({
    id: 'ice-rink-breakaway',
    emoji: '🏒',
    name: 'Ice Rink Breakaway',
    category: 'accents',
    popularity: 173,
    tags: ['hockey stick', 'blue line', 'frozen rink', 'puck chase', 'goal lamp'],
  }),
  createEmoji({
    id: 'field-hockey-loop',
    emoji: '🏑',
    name: 'Field Hockey Loop',
    category: 'accents',
    popularity: 174,
    tags: ['field hockey', 'turf run', 'sweep shot', 'team drill', 'sideline cheer'],
  }),
  createEmoji({
    id: 'lacrosse-stick-stand',
    emoji: '🥍',
    name: 'Lacrosse Stick Stand',
    category: 'accents',
    popularity: 175,
    tags: ['lacrosse', 'crease dive', 'mesh pocket', 'fast break', 'sideline tape'],
  }),
  createEmoji({
    id: 'cricket-crease-call',
    emoji: '🏏',
    name: 'Cricket Crease Call',
    category: 'accents',
    popularity: 176,
    tags: ['cricket bat', 'wicket watch', 'crease chalk', 'tea break', 'pitch read'],
  }),
  createEmoji({
    id: 'table-tennis-spark',
    emoji: '🏓',
    name: 'Table Tennis Spark',
    category: 'accents',
    popularity: 177,
    tags: ['table tennis', 'spin serve', 'ping pong', 'fast rally', 'paddle snap'],
  }),
  createEmoji({
    id: 'badminton-feather-arc',
    emoji: '🏸',
    name: 'Badminton Feather Arc',
    category: 'accents',
    popularity: 178,
    tags: ['badminton', 'shuttle flight', 'net drop', 'clear shot', 'night court'],
  }),
  createEmoji({
    id: 'garden-ring-bout',
    emoji: '🥊',
    name: 'Garden Ring Bout',
    category: 'accents',
    popularity: 179,
    tags: ['boxing gloves', 'sparring bell', 'footwork', 'training ring', 'fight night'],
  }),
  createEmoji({
    id: 'dojo-discipline-hall',
    emoji: '🥋',
    name: 'Dojo Discipline Hall',
    category: 'accents',
    popularity: 180,
    tags: ['martial arts', 'belt rack', 'tatami mat', 'bow respect', 'kata flow'],
  }),
  createEmoji({
    id: 'curling-stone-slide',
    emoji: '🥌',
    name: 'Curling Stone Slide',
    category: 'accents',
    popularity: 181,
    tags: ['curling stone', 'sheet of ice', 'broom sweep', 'hammer shot', 'house rings'],
  }),
  createEmoji({
    id: 'handball-goal-sprint',
    emoji: '🤾',
    name: 'Handball Goal Sprint',
    category: 'accents',
    popularity: 182,
    tags: ['handball', 'court dash', 'goal zone', 'team press', 'quick pass'],
  }),
  createEmoji({
    id: 'acro-gym-circle',
    emoji: '🤸',
    name: 'Acro Gym Circle',
    category: 'accents',
    popularity: 183,
    tags: ['gymnastics', 'cartwheel', 'balance beam', 'spring floor', 'tumbling arc'],
  }),
  createEmoji({
    id: 'fencing-piste-poise',
    emoji: '🤺',
    name: 'Fencing Piste Poise',
    category: 'accents',
    popularity: 184,
    tags: ['fencing', 'foil salute', 'piste strip', 'en garde', 'parry riposte'],
  }),
  createEmoji({
    id: 'alpine-ski-line',
    emoji: '⛷️',
    name: 'Alpine Ski Line',
    category: 'accents',
    popularity: 185,
    tags: ['ski slope', 'powder trail', 'carving turn', 'mountain run', 'lift pass'],
  }),
  createEmoji({
    id: 'snowboard-ridge-drift',
    emoji: '🏂',
    name: 'Snowboard Ridge Drift',
    category: 'accents',
    popularity: 186,
    tags: ['snowboard', 'halfpipe', 'fresh snow', 'winter session', 'alpine air'],
  }),
  createEmoji({
    id: 'swim-lane-splash',
    emoji: '🏊',
    name: 'Swim Lane Splash',
    category: 'accents',
    popularity: 187,
    tags: ['swimming', 'lap lane', 'pool deck', 'goggles', 'cool plunge'],
  }),
  createEmoji({
    id: 'rowing-shell-crew',
    emoji: '🚣',
    name: 'Rowing Shell Crew',
    category: 'accents',
    popularity: 188,
    tags: ['rowing', 'oar stroke', 'river glide', 'coxswain call', 'team rhythm'],
  }),
  createEmoji({
    id: 'peloton-loop-track',
    emoji: '🚴',
    name: 'Peloton Loop Track',
    category: 'accents',
    popularity: 189,
    tags: ['cycling', 'loop course', 'draft line', 'hill climb', 'finish sprint'],
  }),
  createEmoji({
    id: 'archery-range-mark',
    emoji: '🏹',
    name: 'Archery Range Mark',
    category: 'accents',
    popularity: 190,
    tags: ['archery', 'target ring', 'bow string', 'steady aim', 'arrow flight'],
  }),
  createEmoji({
    id: 'riverbank-anglers-spot',
    emoji: '🎣',
    name: 'Riverbank Angler Spot',
    category: 'accents',
    popularity: 191,
    tags: ['fishing pole', 'quiet brook', 'bobber drift', 'fresh catch', 'streamside rest'],
  }),
  createEmoji({
    id: 'greenway-putting-cup',
    emoji: '⛳',
    name: 'Greenway Putting Cup',
    category: 'accents',
    popularity: 192,
    tags: ['golf green', 'flag pin', 'short game', 'gentle slope', 'birdie chance'],
  }),
  createEmoji({
    id: 'crystal-hourglass',
    emoji: '⏳',
    name: 'Crystal Hourglass',
    category: 'accents',
    popularity: 193,
    tags: ['hourglass', 'time flow', 'sand drift', 'patient wait', 'zen timer'],
  }),
  createEmoji({
    id: 'alarm-bell-chime',
    emoji: '⏰',
    name: 'Alarm Bell Chime',
    category: 'accents',
    popularity: 194,
    tags: ['alarm clock', 'morning bell', 'wake time', 'clockface', 'daily routine'],
  }),
  createEmoji({
    id: 'stopwatch-sprint',
    emoji: '⏱️',
    name: 'Stopwatch Sprint',
    category: 'accents',
    popularity: 195,
    tags: ['stopwatch', 'timer', 'race clock', 'lap time', 'precision count'],
  }),
  createEmoji({
    id: 'compass-rose-guide',
    emoji: '🧭',
    name: 'Compass Rose Guide',
    category: 'accents',
    popularity: 196,
    tags: ['compass', 'navigation', 'direction finder', 'trail guide', 'north star'],
  }),
  createEmoji({
    id: 'telescope-starwatch',
    emoji: '🔭',
    name: 'Telescope Starwatch',
    category: 'accents',
    popularity: 197,
    tags: ['telescope', 'stargazing', 'night sky', 'observatory', 'cosmic view'],
  }),
  createEmoji({
    id: 'microscope-vista',
    emoji: '🔬',
    name: 'Microscope Vista',
    category: 'accents',
    popularity: 198,
    tags: ['microscope', 'close study', 'lab work', 'tiny world', 'discovery'],
  }),
  createEmoji({
    id: 'anchor-harbor',
    emoji: '⚓',
    name: 'Anchor Harbor',
    category: 'features',
    popularity: 199,
    tags: ['anchor', 'harbor dock', 'mooring', 'ship rest', 'nautical'],
  }),
  createEmoji({
    id: 'gear-mechanism',
    emoji: '⚙️',
    name: 'Gear Mechanism',
    category: 'accents',
    popularity: 200,
    tags: ['gear', 'mechanical', 'clockwork', 'settings', 'machinery'],
  }),
  createEmoji({
    id: 'toolbox-workshop',
    emoji: '🧰',
    name: 'Toolbox Workshop',
    category: 'features',
    popularity: 201,
    tags: ['toolbox', 'workshop', 'repair kit', 'handy tools', 'builder box'],
  }),
  createEmoji({
    id: 'hammer-craft',
    emoji: '🔨',
    name: 'Hammer Craft',
    category: 'accents',
    popularity: 202,
    tags: ['hammer', 'building tool', 'craft work', 'nail drive', 'workshop'],
  }),
  createEmoji({
    id: 'wrench-adjust',
    emoji: '🔧',
    name: 'Wrench Adjust',
    category: 'accents',
    popularity: 203,
    tags: ['wrench', 'adjustment', 'mechanical fix', 'tool twist', 'repair'],
  }),
  createEmoji({
    id: 'saw-woodwork',
    emoji: '🪚',
    name: 'Saw Woodwork',
    category: 'accents',
    popularity: 204,
    tags: ['saw', 'woodworking', 'carpenter tool', 'cut line', 'builder craft'],
  }),
  createEmoji({
    id: 'ladder-climb',
    emoji: '🪜',
    name: 'Ladder Climb',
    category: 'features',
    popularity: 205,
    tags: ['ladder', 'step up', 'roof access', 'climb tool', 'height reach'],
  }),
  createEmoji({
    id: 'paintbrush-stroke',
    emoji: '🖌️',
    name: 'Paintbrush Stroke',
    category: 'accents',
    popularity: 206,
    tags: ['paintbrush', 'art tool', 'creative stroke', 'color sweep', 'artistic'],
  }),
  createEmoji({
    id: 'crayon-sketch',
    emoji: '🖍️',
    name: 'Crayon Sketch',
    category: 'accents',
    popularity: 207,
    tags: ['crayon', 'wax color', 'child art', 'drawing tool', 'colorful mark'],
  }),
  createEmoji({
    id: 'pencil-draft',
    emoji: '✏️',
    name: 'Pencil Draft',
    category: 'accents',
    popularity: 208,
    tags: ['pencil', 'writing tool', 'sketch line', 'note taking', 'draft work'],
  }),
  createEmoji({
    id: 'pen-signature',
    emoji: '🖊️',
    name: 'Pen Signature',
    category: 'accents',
    popularity: 209,
    tags: ['pen', 'ink writing', 'signature', 'formal note', 'script line'],
  }),
  createEmoji({
    id: 'scroll-ancient',
    emoji: '📜',
    name: 'Scroll Ancient',
    category: 'accents',
    popularity: 210,
    tags: ['scroll', 'ancient text', 'parchment', 'historic document', 'rolled paper'],
  }),
  createEmoji({
    id: 'book-library',
    emoji: '📖',
    name: 'Book Library',
    category: 'accents',
    popularity: 211,
    tags: ['open book', 'reading', 'library', 'story pages', 'knowledge'],
  }),
  createEmoji({
    id: 'notebook-journal',
    emoji: '📓',
    name: 'Notebook Journal',
    category: 'accents',
    popularity: 212,
    tags: ['notebook', 'journal', 'diary', 'note pages', 'personal log'],
  }),
  createEmoji({
    id: 'bookmark-tab',
    emoji: '🔖',
    name: 'Bookmark Tab',
    category: 'accents',
    popularity: 213,
    tags: ['bookmark', 'page marker', 'ribbon tab', 'reading spot', 'save page'],
  }),
  createEmoji({
    id: 'magnifying-search',
    emoji: '🔍',
    name: 'Magnifying Search',
    category: 'accents',
    popularity: 214,
    tags: ['magnifying glass', 'search', 'inspect', 'detective', 'close look'],
  }),
  createEmoji({
    id: 'key-unlock',
    emoji: '🔑',
    name: 'Key Unlock',
    category: 'accents',
    popularity: 215,
    tags: ['key', 'unlock', 'access', 'door opener', 'secret entry'],
  }),
  createEmoji({
    id: 'lock-secure',
    emoji: '🔒',
    name: 'Lock Secure',
    category: 'accents',
    popularity: 216,
    tags: ['lock', 'secure', 'padlock', 'safety', 'protect'],
  }),
  createEmoji({
    id: 'gift-surprise',
    emoji: '🎁',
    name: 'Gift Surprise',
    category: 'accents',
    popularity: 217,
    tags: ['gift box', 'present', 'wrapped surprise', 'celebration', 'ribbon bow'],
  }),
  createEmoji({
    id: 'trophy-victory',
    emoji: '🏆',
    name: 'Trophy Victory',
    category: 'accents',
    popularity: 218,
    tags: ['trophy', 'victory cup', 'champion', 'first place', 'winner'],
  }),
  createEmoji({
    id: 'medal-honor',
    emoji: '🏅',
    name: 'Medal Honor',
    category: 'accents',
    popularity: 219,
    tags: ['medal', 'honor', 'achievement', 'golden award', 'champion badge'],
  }),
  createEmoji({
    id: 'crown-royal',
    emoji: '👑',
    name: 'Crown Royal',
    category: 'accents',
    popularity: 220,
    tags: ['crown', 'royalty', 'king queen', 'jeweled peak', 'regal'],
  }),
  createEmoji({
    id: 'gem-sparkle',
    emoji: '💎',
    name: 'Gem Sparkle',
    category: 'accents',
    popularity: 221,
    tags: ['gem', 'diamond', 'precious stone', 'sparkle shine', 'treasure'],
  }),
  createEmoji({
    id: 'bell-chime',
    emoji: '🔔',
    name: 'Bell Chime',
    category: 'accents',
    popularity: 222,
    tags: ['bell', 'chime', 'ring tone', 'notification', 'alert sound'],
  }),
  createEmoji({
    id: 'horn-fanfare',
    emoji: '📯',
    name: 'Horn Fanfare',
    category: 'accents',
    popularity: 223,
    tags: ['horn', 'fanfare', 'announcement', 'herald call', 'brass blast'],
  }),
  createEmoji({
    id: 'drum-rhythm',
    emoji: '🥁',
    name: 'Drum Rhythm',
    category: 'accents',
    popularity: 224,
    tags: ['drum', 'percussion', 'beat', 'rhythm section', 'musical pulse'],
  }),
  createEmoji({
    id: 'guitar-strum',
    emoji: '🎸',
    name: 'Guitar Strum',
    category: 'accents',
    popularity: 225,
    tags: ['guitar', 'strings', 'musical instrument', 'chord strum', 'melody'],
  }),
  createEmoji({
    id: 'violin-bow',
    emoji: '🎻',
    name: 'Violin Bow',
    category: 'accents',
    popularity: 226,
    tags: ['violin', 'bow strings', 'classical music', 'orchestra', 'melody'],
  }),
  createEmoji({
    id: 'trumpet-brass',
    emoji: '🎺',
    name: 'Trumpet Brass',
    category: 'accents',
    popularity: 227,
    tags: ['trumpet', 'brass horn', 'fanfare', 'jazz', 'bright sound'],
  }),
  createEmoji({
    id: 'saxophone-jazz',
    emoji: '🎷',
    name: 'Saxophone Jazz',
    category: 'accents',
    popularity: 228,
    tags: ['saxophone', 'jazz', 'smooth sound', 'brass reed', 'melody'],
  }),
  createEmoji({
    id: 'musical-note',
    emoji: '🎵',
    name: 'Musical Note',
    category: 'accents',
    popularity: 229,
    tags: ['music note', 'melody', 'tune', 'song', 'harmony'],
  }),
  createEmoji({
    id: 'headphone-listen',
    emoji: '🎧',
    name: 'Headphone Listen',
    category: 'accents',
    popularity: 230,
    tags: ['headphones', 'listen', 'music player', 'audio', 'sound immersion'],
  }),
  createEmoji({
    id: 'microphone-stage',
    emoji: '🎤',
    name: 'Microphone Stage',
    category: 'accents',
    popularity: 231,
    tags: ['microphone', 'stage', 'singing', 'performance', 'voice'],
  }),
  createEmoji({
    id: 'clapper-action',
    emoji: '🎬',
    name: 'Clapper Action',
    category: 'accents',
    popularity: 232,
    tags: ['movie clapper', 'film', 'action', 'cinema', 'director cut'],
  }),
  createEmoji({
    id: 'camera-capture',
    emoji: '📷',
    name: 'Camera Capture',
    category: 'accents',
    popularity: 233,
    tags: ['camera', 'photo', 'capture', 'snapshot', 'memory'],
  }),
  createEmoji({
    id: 'video-recorder',
    emoji: '📹',
    name: 'Video Recorder',
    category: 'accents',
    popularity: 234,
    tags: ['video camera', 'recording', 'film', 'capture motion', 'home movie'],
  }),
  createEmoji({
    id: 'game-controller',
    emoji: '🎮',
    name: 'Game Controller',
    category: 'accents',
    popularity: 235,
    tags: ['game controller', 'gaming', 'player', 'console', 'joystick'],
  }),
  createEmoji({
    id: 'dice-roll',
    emoji: '🎲',
    name: 'Dice Roll',
    category: 'accents',
    popularity: 236,
    tags: ['dice', 'game piece', 'chance', 'roll luck', 'board game'],
  }),
  createEmoji({
    id: 'puzzle-piece',
    emoji: '🧩',
    name: 'Puzzle Piece',
    category: 'accents',
    popularity: 237,
    tags: ['puzzle piece', 'jigsaw', 'fit together', 'solve', 'connection'],
  }),
  createEmoji({
    id: 'teddy-bear-hug',
    emoji: '🧸',
    name: 'Teddy Bear Hug',
    category: 'accents',
    popularity: 238,
    tags: ['teddy bear', 'plush toy', 'comfort', 'childhood', 'soft hug'],
  }),
  createEmoji({
    id: 'pinata-party',
    emoji: '🪅',
    name: 'Pinata Party',
    category: 'accents',
    popularity: 239,
    tags: ['pinata', 'party game', 'candy burst', 'celebration', 'colorful'],
  }),
  createEmoji({
    id: 'magic-wand',
    emoji: '🪄',
    name: 'Magic Wand',
    category: 'accents',
    popularity: 240,
    tags: ['magic wand', 'spell cast', 'sparkle', 'illusion', 'enchantment'],
  }),
  createEmoji({
    id: 'crystal-ball',
    emoji: '🔮',
    name: 'Crystal Ball',
    category: 'accents',
    popularity: 241,
    tags: ['crystal ball', 'fortune', 'mystic vision', 'future sight', 'prophecy'],
  }),
  createEmoji({
    id: 'jack-lantern',
    emoji: '🎃',
    name: 'Jack Lantern',
    category: 'accents',
    popularity: 242,
    tags: ['jack-o-lantern', 'pumpkin', 'carved face', 'autumn', 'spooky glow'],
  }),
  createEmoji({
    id: 'wrapped-gift-bow',
    emoji: '🎀',
    name: 'Wrapped Gift Bow',
    category: 'accents',
    popularity: 243,
    tags: ['ribbon', 'bow tie', 'gift wrap', 'decoration', 'present topper'],
  }),
  createEmoji({
    id: 'envelope-letter',
    emoji: '✉️',
    name: 'Envelope Letter',
    category: 'accents',
    popularity: 244,
    tags: ['envelope', 'letter', 'mail', 'message', 'correspondence'],
  }),
  createEmoji({
    id: 'postbox-mail',
    emoji: '📮',
    name: 'Postbox Mail',
    category: 'features',
    popularity: 245,
    tags: ['postbox', 'mailbox', 'letter drop', 'postal service', 'send mail'],
  }),
  createEmoji({
    id: 'package-delivery',
    emoji: '📦',
    name: 'Package Delivery',
    category: 'accents',
    popularity: 246,
    tags: ['package', 'box', 'delivery', 'parcel', 'shipping'],
  }),
  createEmoji({
    id: 'shopping-cart',
    emoji: '🛒',
    name: 'Shopping Cart',
    category: 'accents',
    popularity: 247,
    tags: ['shopping cart', 'grocery', 'market', 'purchase', 'store trip'],
  }),
  createEmoji({
    id: 'shopping-bags',
    emoji: '🛍️',
    name: 'Shopping Bags',
    category: 'accents',
    popularity: 248,
    tags: ['shopping bags', 'retail', 'purchase', 'store haul', 'boutique'],
  }),
  createEmoji({
    id: 'flags-bunting',
    emoji: '🎏',
    name: 'Flags Bunting',
    category: 'accents',
    popularity: 249,
    tags: ['carp streamer', 'flags', 'festival banners', 'wind stream', 'celebration'],
  }),
  createEmoji({
    id: 'ribbon-reminder',
    emoji: '🎗️',
    name: 'Ribbon Reminder',
    category: 'accents',
    popularity: 250,
    tags: ['reminder ribbon', 'awareness', 'cause', 'support badge', 'memorial'],
  }),
  createEmoji({
    id: 'ticket-admit',
    emoji: '🎟️',
    name: 'Ticket Admit',
    category: 'accents',
    popularity: 251,
    tags: ['admission ticket', 'entry pass', 'event', 'show stub', 'access'],
  }),
  createEmoji({
    id: 'military-medal',
    emoji: '🎖️',
    name: 'Military Medal',
    category: 'accents',
    popularity: 252,
    tags: ['military medal', 'honor badge', 'service', 'valor', 'decoration'],
  }),
  createEmoji({
    id: 'direct-hit',
    emoji: '🎯',
    name: 'Direct Hit',
    category: 'accents',
    popularity: 253,
    tags: ['bullseye', 'target', 'direct hit', 'aim', 'goal reached'],
  }),
  createEmoji({
    id: 'checkered-flag',
    emoji: '🏁',
    name: 'Checkered Flag',
    category: 'accents',
    popularity: 254,
    tags: ['checkered flag', 'finish line', 'race end', 'victory', 'complete'],
  }),
  createEmoji({
    id: 'triangular-flag',
    emoji: '🚩',
    name: 'Triangular Flag',
    category: 'accents',
    popularity: 255,
    tags: ['triangular flag', 'marker', 'alert', 'signal post', 'warning'],
  }),
  createEmoji({
    id: 'crossed-flags',
    emoji: '🎌',
    name: 'Crossed Flags',
    category: 'accents',
    popularity: 256,
    tags: ['crossed flags', 'celebration', 'festival', 'dual banner', 'ceremony'],
  }),
  createEmoji({
    id: 'pirate-flag',
    emoji: '🏴‍☠️',
    name: 'Pirate Flag',
    category: 'accents',
    popularity: 257,
    tags: ['pirate flag', 'jolly roger', 'skull bones', 'adventure', 'treasure hunt'],
  }),
  createEmoji({
    id: 'artist-palette',
    emoji: '🎨',
    name: 'Artist Palette',
    category: 'accents',
    popularity: 258,
    tags: ['palette', 'paint colors', 'art mixing', 'creative tool', 'brush holder'],
  }),
  createEmoji({
    id: 'sewing-needle',
    emoji: '🪡',
    name: 'Sewing Needle',
    category: 'accents',
    popularity: 259,
    tags: ['sewing needle', 'thread', 'stitch work', 'craft tool', 'mending'],
  }),
  createEmoji({
    id: 'yarn-ball',
    emoji: '🧶',
    name: 'Yarn Ball',
    category: 'accents',
    popularity: 260,
    tags: ['yarn', 'knitting', 'wool ball', 'craft material', 'thread roll'],
  }),
  createEmoji({
    id: 'knot-tie',
    emoji: '🪢',
    name: 'Knot Tie',
    category: 'accents',
    popularity: 261,
    tags: ['knot', 'rope tie', 'binding', 'secure loop', 'sailor knot'],
  }),
  createEmoji({
    id: 'safety-pin',
    emoji: '🧷',
    name: 'Safety Pin',
    category: 'accents',
    popularity: 262,
    tags: ['safety pin', 'clasp', 'fastener', 'quick fix', 'secure hold'],
  }),
  createEmoji({
    id: 'broom-sweep',
    emoji: '🧹',
    name: 'Broom Sweep',
    category: 'accents',
    popularity: 263,
    tags: ['broom', 'sweep', 'clean tool', 'tidy up', 'floor brush'],
  }),
  createEmoji({
    id: 'soap-bubble',
    emoji: '🧼',
    name: 'Soap Bubble',
    category: 'accents',
    popularity: 264,
    tags: ['soap', 'clean bar', 'wash', 'bubble lather', 'fresh scent'],
  }),
  createEmoji({
    id: 'sponge-scrub',
    emoji: '🧽',
    name: 'Sponge Scrub',
    category: 'accents',
    popularity: 265,
    tags: ['sponge', 'scrub tool', 'clean wipe', 'absorbent', 'dish helper'],
  }),
  createEmoji({
    id: 'plunger-fix',
    emoji: '🪠',
    name: 'Plunger Fix',
    category: 'accents',
    popularity: 266,
    tags: ['plunger', 'drain tool', 'plumbing', 'quick fix', 'suction cup'],
  }),
  createEmoji({
    id: 'toothbrush-clean',
    emoji: '🪥',
    name: 'Toothbrush Clean',
    category: 'accents',
    popularity: 267,
    tags: ['toothbrush', 'dental care', 'clean teeth', 'morning routine', 'bristle brush'],
  }),
  createEmoji({
    id: 'shower-spray',
    emoji: '🚿',
    name: 'Shower Spray',
    category: 'accents',
    popularity: 268,
    tags: ['shower', 'water spray', 'bath time', 'rinse off', 'fresh clean'],
  }),
  createEmoji({
    id: 'toilet-seat',
    emoji: '🚽',
    name: 'Toilet Seat',
    category: 'accents',
    popularity: 269,
    tags: ['toilet', 'restroom', 'bathroom', 'facilities', 'comfort station'],
  }),
  createEmoji({
    id: 'roll-paper',
    emoji: '🧻',
    name: 'Roll Paper',
    category: 'accents',
    popularity: 270,
    tags: ['toilet paper', 'tissue roll', 'bathroom essential', 'soft sheets', 'paper roll'],
  }),
  createEmoji({
    id: 'umbrella-rain',
    emoji: '☔',
    name: 'Umbrella Rain',
    category: 'accents',
    popularity: 271,
    tags: ['umbrella', 'rain cover', 'weather shield', 'storm protection', 'stay dry'],
  }),
  createEmoji({
    id: 'snowflake-crystal',
    emoji: '❄️',
    name: 'Snowflake Crystal',
    category: 'accents',
    popularity: 272,
    tags: ['snowflake', 'ice crystal', 'winter', 'unique pattern', 'frost'],
  }),
  createEmoji({
    id: 'snowman-build',
    emoji: '⛄',
    name: 'Snowman Build',
    category: 'accents',
    popularity: 273,
    tags: ['snowman', 'winter friend', 'snow sculpture', 'carrot nose', 'coal smile'],
  }),
  createEmoji({
    id: 'comet-streak',
    emoji: '☄️',
    name: 'Comet Streak',
    category: 'accents',
    popularity: 274,
    tags: ['comet', 'meteor', 'space rock', 'tail streak', 'cosmic visitor'],
  }),
  createEmoji({
    id: 'lightning-bolt',
    emoji: '⚡',
    name: 'Lightning Bolt',
    category: 'accents',
    popularity: 275,
    tags: ['lightning', 'thunderbolt', 'electric flash', 'storm power', 'energy'],
  }),
  createEmoji({
    id: 'tornado-spiral',
    emoji: '🌪️',
    name: 'Tornado Spiral',
    category: 'scenery',
    popularity: 276,
    tags: ['tornado', 'twister', 'whirlwind', 'storm spiral', 'weather vortex'],
  }),
  createEmoji({
    id: 'cyclone-spin',
    emoji: '🌀',
    name: 'Cyclone Spin',
    category: 'scenery',
    popularity: 277,
    tags: ['cyclone', 'hurricane', 'typhoon', 'spiral storm', 'wind pattern'],
  }),
  createEmoji({
    id: 'foggy-mist',
    emoji: '🌁',
    name: 'Foggy Mist',
    category: 'scenery',
    popularity: 278,
    tags: ['fog', 'misty', 'low cloud', 'morning haze', 'limited view'],
  }),
  createEmoji({
    id: 'wind-face',
    emoji: '🌬️',
    name: 'Wind Face',
    category: 'scenery',
    popularity: 279,
    tags: ['wind', 'blow', 'breeze', 'air current', 'gust'],
  }),
  createEmoji({
    id: 'hot-springs',
    emoji: '♨️',
    name: 'Hot Springs',
    category: 'features',
    popularity: 280,
    tags: ['hot springs', 'steam', 'thermal bath', 'spa water', 'mineral soak'],
  }),
  createEmoji({
    id: 'yo-yo-spin',
    emoji: '🪀',
    name: 'Yo-Yo Spin',
    category: 'accents',
    popularity: 281,
    tags: ['yo-yo', 'string toy', 'trick spin', 'loop play', 'classic game'],
  }),
  createEmoji({
    id: 'boomerang-return',
    emoji: '🪃',
    name: 'Boomerang Return',
    category: 'accents',
    popularity: 282,
    tags: ['boomerang', 'throw return', 'curved flight', 'sport tool', 'arc path'],
  }),
  createEmoji({
    id: 'sled-snow-run',
    emoji: '🛷',
    name: 'Sled Snow Run',
    category: 'accents',
    popularity: 283,
    tags: ['sled', 'snow slide', 'winter ride', 'hill rush', 'toboggan'],
  }),
  createEmoji({
    id: 'ice-skate-glide',
    emoji: '⛸️',
    name: 'Ice Skate Glide',
    category: 'accents',
    popularity: 284,
    tags: ['ice skate', 'rink glide', 'blade edge', 'winter sport', 'figure eight'],
  }),
  createEmoji({
    id: 'bowling-strike',
    emoji: '🎳',
    name: 'Bowling Strike',
    category: 'accents',
    popularity: 285,
    tags: ['bowling', 'strike', 'lane roll', 'pin crash', 'spare game'],
  }),
  createEmoji({
    id: 'billiards-cue',
    emoji: '🎱',
    name: 'Billiards Cue',
    category: 'accents',
    popularity: 286,
    tags: ['billiards', 'pool ball', 'eight ball', 'cue shot', 'table game'],
  }),
  createEmoji({
    id: 'skateboard-trick',
    emoji: '🛹',
    name: 'Skateboard Trick',
    category: 'accents',
    popularity: 287,
    tags: ['skateboard', 'trick flip', 'street sport', 'ramp ride', 'deck art'],
  }),
  createEmoji({
    id: 'parachute-glide',
    emoji: '🪂',
    name: 'Parachute Glide',
    category: 'accents',
    popularity: 288,
    tags: ['parachute', 'skydive', 'air drift', 'safe landing', 'canopy float'],
  }),
  createEmoji({
    id: 'mountain-bike-trail',
    emoji: '🚵',
    name: 'Mountain Bike Trail',
    category: 'accents',
    popularity: 289,
    tags: ['mountain biking', 'trail ride', 'off-road', 'adventure cycling', 'rough terrain'],
  }),
  createEmoji({
    id: 'rock-climbing-wall',
    emoji: '🧗',
    name: 'Rock Climbing Wall',
    category: 'accents',
    popularity: 290,
    tags: ['rock climbing', 'wall climb', 'bouldering', 'grip hold', 'ascent'],
  }),
  createEmoji({
    id: 'surfing-wave-ride',
    emoji: '🏄',
    name: 'Surfing Wave Ride',
    category: 'accents',
    popularity: 291,
    tags: ['surfing', 'wave ride', 'beach sport', 'ocean', 'board balance'],
  }),
  createEmoji({
    id: 'kayak-paddle-tour',
    emoji: '🛶',
    name: 'Kayak Paddle Tour',
    category: 'accents',
    popularity: 292,
    tags: ['kayak', 'paddle sport', 'river run', 'water trail', 'solo boat'],
  }),
  createEmoji({
    id: 'flying-kite',
    emoji: '🪁',
    name: 'Flying Kite',
    category: 'accents',
    popularity: 293,
    tags: ['kite', 'wind toy', 'sky float', 'string pull', 'breeze dance'],
  }),
  createEmoji({
    id: 'magic-crystal',
    emoji: '🔮',
    name: 'Magic Crystal',
    category: 'accents',
    popularity: 294,
    tags: ['crystal orb', 'fortune telling', 'mystic', 'prophecy', 'vision sphere'],
  }),
  createEmoji({
    id: 'party-confetti',
    emoji: '🎊',
    name: 'Party Confetti',
    category: 'accents',
    popularity: 295,
    tags: ['confetti ball', 'party time', 'celebration burst', 'festive', 'joy scatter'],
  }),
  createEmoji({
    id: 'wrapped-present',
    emoji: '🎁',
    name: 'Wrapped Present',
    category: 'accents',
    popularity: 296,
    tags: ['present box', 'gift wrap', 'surprise', 'birthday', 'special delivery'],
  }),
  createEmoji({
    id: 'birthday-cake',
    emoji: '🎂',
    name: 'Birthday Cake',
    category: 'accents',
    popularity: 297,
    tags: ['birthday cake', 'candles', 'celebration', 'party dessert', 'wish time'],
  }),
  createEmoji({
    id: 'japanese-dolls',
    emoji: '🎎',
    name: 'Japanese Dolls',
    category: 'accents',
    popularity: 298,
    tags: ['dolls', 'traditional', 'festival display', 'cultural', 'ceremonial'],
  }),
  createEmoji({
    id: 'wind-chime-breeze',
    emoji: '🎐',
    name: 'Wind Chime Breeze',
    category: 'accents',
    popularity: 299,
    tags: ['wind chime', 'hanging bell', 'breeze sound', 'garden music', 'gentle tinkle'],
  }),
  createEmoji({
    id: 'balloon-float',
    emoji: '🎈',
    name: 'Balloon Float',
    category: 'accents',
    popularity: 300,
    tags: ['balloon', 'party float', 'celebration', 'helium rise', 'festive air'],
  }),
  createEmoji({
    id: 'ribbon-curl',
    emoji: '🎀',
    name: 'Ribbon Curl',
    category: 'accents',
    popularity: 301,
    tags: ['ribbon bow', 'gift wrap', 'decoration', 'pretty curl', 'present topper'],
  }),
  createEmoji({
    id: 'sparkler-light',
    emoji: '🎇',
    name: 'Sparkler Light',
    category: 'accents',
    popularity: 302,
    tags: ['sparkler', 'firework', 'celebration light', 'handheld spark', 'festive glow'],
  }),
  createEmoji({
    id: 'firework-burst',
    emoji: '🎆',
    name: 'Firework Burst',
    category: 'accents',
    popularity: 303,
    tags: ['fireworks', 'sky burst', 'celebration', 'night display', 'colorful explosion'],
  }),
  createEmoji({
    id: 'tanabata-tree',
    emoji: '🎋',
    name: 'Tanabata Tree',
    category: 'plants',
    popularity: 304,
    tags: ['bamboo', 'decoration tree', 'festival', 'wish branch', 'celebration'],
  }),
  createEmoji({
    id: 'pine-decoration',
    emoji: '🎍',
    name: 'Pine Decoration',
    category: 'plants',
    popularity: 305,
    tags: ['pine', 'bamboo arrangement', 'traditional', 'new year', 'ceremonial'],
  }),
  createEmoji({
    id: 'carp-streamer',
    emoji: '🎏',
    name: 'Carp Streamer',
    category: 'accents',
    popularity: 306,
    tags: ['koi banner', 'wind sock', 'festival flag', 'traditional', 'flying fish'],
  }),
  createEmoji({
    id: 'red-envelope',
    emoji: '🧧',
    name: 'Red Envelope',
    category: 'accents',
    popularity: 307,
    tags: ['gift envelope', 'lucky money', 'celebration', 'traditional gift', 'prosperity'],
  }),
  createEmoji({
    id: 'nazar-amulet',
    emoji: '🧿',
    name: 'Nazar Amulet',
    category: 'accents',
    popularity: 308,
    tags: ['evil eye', 'protection charm', 'talisman', 'blue bead', 'good luck'],
  }),
  createEmoji({
    id: 'hamsa-hand',
    emoji: '🪬',
    name: 'Hamsa Hand',
    category: 'accents',
    popularity: 309,
    tags: ['hamsa', 'hand symbol', 'protection', 'blessing', 'good fortune'],
  }),
  createEmoji({
    id: 'prayer-beads',
    emoji: '📿',
    name: 'Prayer Beads',
    category: 'accents',
    popularity: 310,
    tags: ['beads', 'meditation', 'spiritual', 'counting chain', 'peaceful prayer'],
  }),
  createEmoji({
    id: 'amphora-vase',
    emoji: '🏺',
    name: 'Amphora Vase',
    category: 'accents',
    popularity: 311,
    tags: ['ancient vase', 'pottery', 'classical vessel', 'historic jar', 'earthenware'],
  }),
  createEmoji({
    id: 'world-map',
    emoji: '🗺️',
    name: 'World Map',
    category: 'accents',
    popularity: 312,
    tags: ['map', 'world view', 'geography', 'exploration', 'atlas spread'],
  }),
  createEmoji({
    id: 'mount-fuji',
    emoji: '🗻',
    name: 'Mount Fuji',
    category: 'scenery',
    popularity: 313,
    tags: ['mountain', 'volcano', 'snow peak', 'majestic summit', 'sacred mountain'],
  }),
  createEmoji({
    id: 'tokyo-tower',
    emoji: '🗼',
    name: 'Tokyo Tower',
    category: 'scenery',
    popularity: 314,
    tags: ['tower', 'landmark', 'city icon', 'tall structure', 'observation deck'],
  }),
  createEmoji({
    id: 'statue-liberty',
    emoji: '🗽',
    name: 'Statue of Liberty',
    category: 'scenery',
    popularity: 315,
    tags: ['statue', 'liberty', 'landmark', 'freedom symbol', 'monument'],
  }),
  createEmoji({
    id: 'moai-statue',
    emoji: '🗿',
    name: 'Moai Statue',
    category: 'scenery',
    popularity: 316,
    tags: ['moai', 'stone head', 'ancient statue', 'easter island', 'mysterious face'],
  }),
  createEmoji({
    id: 'camping-tent',
    emoji: '⛺',
    name: 'Camping Tent',
    category: 'scenery',
    popularity: 317,
    tags: ['tent', 'camping', 'outdoor shelter', 'adventure', 'nature sleep'],
  }),
  createEmoji({
    id: 'fountain-spray',
    emoji: '⛲',
    name: 'Fountain Spray',
    category: 'features',
    popularity: 318,
    tags: ['fountain', 'water spray', 'garden feature', 'decorative water', 'splash'],
  }),
  createEmoji({
    id: 'ferris-wheel',
    emoji: '🎡',
    name: 'Ferris Wheel',
    category: 'accents',
    popularity: 319,
    tags: ['ferris wheel', 'carnival ride', 'observation wheel', 'fun ride', 'city view'],
  }),
  createEmoji({
    id: 'roller-coaster',
    emoji: '🎢',
    name: 'Roller Coaster',
    category: 'accents',
    popularity: 320,
    tags: ['roller coaster', 'thrill ride', 'amusement', 'looping track', 'excitement'],
  }),
  createEmoji({
    id: 'carousel-horse',
    emoji: '🎠',
    name: 'Carousel Horse',
    category: 'accents',
    popularity: 321,
    tags: ['carousel', 'merry-go-round', 'horse ride', 'fair attraction', 'spinning fun'],
  }),
  createEmoji({
    id: 'circus-tent',
    emoji: '🎪',
    name: 'Circus Tent',
    category: 'scenery',
    popularity: 322,
    tags: ['circus', 'big top', 'striped tent', 'performance venue', 'show time'],
  }),
  createEmoji({
    id: 'steam-locomotive',
    emoji: '🚂',
    name: 'Steam Locomotive',
    category: 'accents',
    popularity: 323,
    tags: ['train', 'locomotive', 'steam engine', 'railroad', 'vintage transport'],
  }),
  createEmoji({
    id: 'railway-car',
    emoji: '🚃',
    name: 'Railway Car',
    category: 'accents',
    popularity: 324,
    tags: ['train car', 'passenger car', 'railway', 'transit', 'commuter'],
  }),
  createEmoji({
    id: 'bullet-train',
    emoji: '🚄',
    name: 'Bullet Train',
    category: 'accents',
    popularity: 325,
    tags: ['high-speed train', 'shinkansen', 'fast rail', 'modern transit', 'express'],
  }),
  createEmoji({
    id: 'train-front',
    emoji: '🚅',
    name: 'Train Front',
    category: 'accents',
    popularity: 326,
    tags: ['train', 'front view', 'rail transport', 'locomotive face', 'track runner'],
  }),
  createEmoji({
    id: 'monorail-track',
    emoji: '🚝',
    name: 'Monorail Track',
    category: 'accents',
    popularity: 327,
    tags: ['monorail', 'elevated train', 'single track', 'futuristic transit', 'city transport'],
  }),
  createEmoji({
    id: 'mountain-railway',
    emoji: '🚞',
    name: 'Mountain Railway',
    category: 'accents',
    popularity: 328,
    tags: ['mountain train', 'funicular', 'cable railway', 'hillside transport', 'scenic ride'],
  }),
  createEmoji({
    id: 'tram-car',
    emoji: '🚊',
    name: 'Tram Car',
    category: 'accents',
    popularity: 329,
    tags: ['tram', 'streetcar', 'trolley', 'city rail', 'urban transit'],
  }),
  createEmoji({
    id: 'bus-vehicle',
    emoji: '🚌',
    name: 'Bus Vehicle',
    category: 'accents',
    popularity: 330,
    tags: ['bus', 'public transport', 'city bus', 'passenger vehicle', 'commute'],
  }),
  createEmoji({
    id: 'trolleybus-line',
    emoji: '🚎',
    name: 'Trolleybus Line',
    category: 'accents',
    popularity: 331,
    tags: ['trolleybus', 'electric bus', 'overhead wire', 'city transport', 'eco transit'],
  }),
  createEmoji({
    id: 'minibus-small',
    emoji: '🚐',
    name: 'Minibus Small',
    category: 'accents',
    popularity: 332,
    tags: ['minibus', 'shuttle', 'van', 'small bus', 'group transport'],
  }),
  createEmoji({
    id: 'taxi-cab',
    emoji: '🚕',
    name: 'Taxi Cab',
    category: 'accents',
    popularity: 333,
    tags: ['taxi', 'cab', 'hire car', 'city transport', 'ride service'],
  }),
  createEmoji({
    id: 'police-car',
    emoji: '🚓',
    name: 'Police Car',
    category: 'accents',
    popularity: 334,
    tags: ['police', 'patrol car', 'law enforcement', 'emergency vehicle', 'safety'],
  }),
  createEmoji({
    id: 'ambulance-emergency',
    emoji: '🚑',
    name: 'Ambulance Emergency',
    category: 'accents',
    popularity: 335,
    tags: ['ambulance', 'medical vehicle', 'emergency', 'rescue', 'health transport'],
  }),
  createEmoji({
    id: 'fire-engine',
    emoji: '🚒',
    name: 'Fire Engine',
    category: 'accents',
    popularity: 336,
    tags: ['fire truck', 'firefighter', 'emergency vehicle', 'rescue', 'ladder truck'],
  }),
  createEmoji({
    id: 'delivery-truck',
    emoji: '🚚',
    name: 'Delivery Truck',
    category: 'accents',
    popularity: 337,
    tags: ['truck', 'delivery', 'cargo vehicle', 'transport', 'shipping'],
  }),
  createEmoji({
    id: 'articulated-lorry',
    emoji: '🚛',
    name: 'Articulated Lorry',
    category: 'accents',
    popularity: 338,
    tags: ['semi-truck', 'big rig', 'trailer truck', 'long haul', 'freight'],
  }),
  createEmoji({
    id: 'tractor-farm',
    emoji: '🚜',
    name: 'Tractor Farm',
    category: 'accents',
    popularity: 339,
    tags: ['tractor', 'farm vehicle', 'agriculture', 'field work', 'harvest machine'],
  }),
  createEmoji({
    id: 'racing-car',
    emoji: '🏎️',
    name: 'Racing Car',
    category: 'accents',
    popularity: 340,
    tags: ['race car', 'formula racing', 'speed machine', 'sport car', 'track racer'],
  }),
  createEmoji({
    id: 'motorcycle-bike',
    emoji: '🏍️',
    name: 'Motorcycle Bike',
    category: 'accents',
    popularity: 341,
    tags: ['motorcycle', 'motorbike', 'two-wheeler', 'speed bike', 'road rider'],
  }),
  createEmoji({
    id: 'scooter-motor',
    emoji: '🛵',
    name: 'Scooter Motor',
    category: 'accents',
    popularity: 342,
    tags: ['motor scooter', 'moped', 'city bike', 'light transport', 'urban rider'],
  }),
  createEmoji({
    id: 'bicycle-ride',
    emoji: '🚲',
    name: 'Bicycle Ride',
    category: 'accents',
    popularity: 343,
    tags: ['bicycle', 'bike', 'cycling', 'pedal power', 'eco transport'],
  }),
  createEmoji({
    id: 'kick-scooter',
    emoji: '🛴',
    name: 'Kick Scooter',
    category: 'accents',
    popularity: 344,
    tags: ['scooter', 'kick scooter', 'footboard', 'personal transport', 'urban glide'],
  }),
  createEmoji({
    id: 'sailboat-vessel',
    emoji: '⛵',
    name: 'Sailboat Vessel',
    category: 'accents',
    popularity: 345,
    tags: ['sailboat', 'sailing', 'yacht', 'wind power', 'ocean vessel'],
  }),
  createEmoji({
    id: 'speedboat-fast',
    emoji: '🚤',
    name: 'Speedboat Fast',
    category: 'accents',
    popularity: 346,
    tags: ['speedboat', 'motorboat', 'fast boat', 'water speed', 'marine craft'],
  }),
  createEmoji({
    id: 'ferry-boat',
    emoji: '⛴️',
    name: 'Ferry Boat',
    category: 'accents',
    popularity: 347,
    tags: ['ferry', 'passenger boat', 'water transport', 'harbor crossing', 'marine transit'],
  }),
  createEmoji({
    id: 'ship-vessel',
    emoji: '🚢',
    name: 'Ship Vessel',
    category: 'accents',
    popularity: 348,
    tags: ['ship', 'cruise', 'ocean liner', 'large vessel', 'sea voyage'],
  }),
  createEmoji({
    id: 'airplane-flight',
    emoji: '✈️',
    name: 'Airplane Flight',
    category: 'accents',
    popularity: 349,
    tags: ['airplane', 'aircraft', 'flight', 'air travel', 'sky journey'],
  }),
  createEmoji({
    id: 'small-airplane',
    emoji: '🛩️',
    name: 'Small Airplane',
    category: 'accents',
    popularity: 350,
    tags: ['small plane', 'light aircraft', 'propeller plane', 'private flight', 'sky cruiser'],
  }),
  createEmoji({
    id: 'airplane-departure',
    emoji: '🛫',
    name: 'Airplane Departure',
    category: 'accents',
    popularity: 351,
    tags: ['takeoff', 'departure', 'flight launch', 'ascending plane', 'journey start'],
  }),
  createEmoji({
    id: 'airplane-arrival',
    emoji: '🛬',
    name: 'Airplane Arrival',
    category: 'accents',
    popularity: 352,
    tags: ['landing', 'arrival', 'flight touchdown', 'descending plane', 'journey end'],
  }),
  createEmoji({
    id: 'helicopter-chopper',
    emoji: '🚁',
    name: 'Helicopter Chopper',
    category: 'accents',
    popularity: 353,
    tags: ['helicopter', 'chopper', 'rotorcraft', 'aerial vehicle', 'sky hover'],
  }),
  createEmoji({
    id: 'rocket-launch',
    emoji: '🚀',
    name: 'Rocket Launch',
    category: 'accents',
    popularity: 354,
    tags: ['rocket', 'spacecraft', 'space launch', 'blast off', 'cosmic journey'],
  }),
  createEmoji({
    id: 'flying-saucer',
    emoji: '🛸',
    name: 'Flying Saucer',
    category: 'accents',
    popularity: 355,
    tags: ['UFO', 'alien craft', 'flying saucer', 'extraterrestrial', 'space visitor'],
  }),
  createEmoji({
    id: 'satellite-orbit',
    emoji: '🛰️',
    name: 'Satellite Orbit',
    category: 'accents',
    popularity: 356,
    tags: ['satellite', 'space station', 'orbital device', 'communication', 'sky tech'],
  }),
  createEmoji({
    id: 'seat-chair',
    emoji: '💺',
    name: 'Seat Chair',
    category: 'accents',
    popularity: 357,
    tags: ['seat', 'chair', 'airline seat', 'passenger chair', 'sitting place'],
  }),
  createEmoji({
    id: 'canoe-paddle',
    emoji: '🛶',
    name: 'Canoe Paddle',
    category: 'accents',
    popularity: 358,
    tags: ['canoe', 'kayak', 'paddle boat', 'water craft', 'river vessel'],
  }),
  createEmoji({
    id: 'anchor-marine',
    emoji: '⚓',
    name: 'Anchor Marine',
    category: 'accents',
    popularity: 359,
    tags: ['anchor', 'ship anchor', 'marine tool', 'harbor rest', 'stability'],
  }),
  createEmoji({
    id: 'construction-sign',
    emoji: '🚧',
    name: 'Construction Sign',
    category: 'accents',
    popularity: 360,
    tags: ['construction', 'warning', 'barrier', 'work zone', 'caution sign'],
  }),
  createEmoji({
    id: 'fuel-pump',
    emoji: '⛽',
    name: 'Fuel Pump',
    category: 'accents',
    popularity: 361,
    tags: ['gas pump', 'fuel station', 'petrol', 'refuel', 'energy station'],
  }),
  createEmoji({
    id: 'vertical-light',
    emoji: '🚦',
    name: 'Vertical Light',
    category: 'accents',
    popularity: 362,
    tags: ['traffic light', 'signal', 'stop light', 'intersection', 'road control'],
  }),
  createEmoji({
    id: 'horizontal-light',
    emoji: '🚥',
    name: 'Horizontal Light',
    category: 'accents',
    popularity: 363,
    tags: ['traffic signal', 'horizontal light', 'stop signal', 'road light', 'traffic control'],
  }),
  createEmoji({
    id: 'octagonal-sign',
    emoji: '🛑',
    name: 'Octagonal Sign',
    category: 'accents',
    popularity: 364,
    tags: ['stop sign', 'octagon', 'road sign', 'halt', 'traffic stop'],
  }),
  createEmoji({
    id: 'map-pin',
    emoji: '📍',
    name: 'Map Pin',
    category: 'accents',
    popularity: 365,
    tags: ['pushpin', 'location', 'map marker', 'position pin', 'waypoint'],
  }),
  createEmoji({
    id: 'round-pushpin',
    emoji: '📌',
    name: 'Round Pushpin',
    category: 'accents',
    popularity: 366,
    tags: ['pushpin', 'pin', 'tack', 'notice holder', 'attach point'],
  }),
  createEmoji({
    id: 'steam-train',
    emoji: '🚂',
    name: 'Steam Train',
    category: 'accents',
    popularity: 367,
    tags: ['vintage train', 'steam power', 'old locomotive', 'railway history', 'iron horse'],
  }),
  createEmoji({
    id: 'brick-wall',
    emoji: '🧱',
    name: 'Brick Wall',
    category: 'scenery',
    popularity: 368,
    tags: ['brick', 'wall', 'construction', 'building block', 'masonry'],
  }),
  createEmoji({
    id: 'wood-plank',
    emoji: '🪵',
    name: 'Wood Plank',
    category: 'scenery',
    popularity: 369,
    tags: ['wood', 'log', 'timber', 'lumber', 'natural material'],
  }),
  createEmoji({
    id: 'rock-stone',
    emoji: '🪨',
    name: 'Rock Stone',
    category: 'scenery',
    popularity: 370,
    tags: ['rock', 'stone', 'boulder', 'mineral', 'earth element'],
  }),
  createEmoji({
    id: 'thread-spool',
    emoji: '🧵',
    name: 'Thread Spool',
    category: 'accents',
    popularity: 371,
    tags: ['thread', 'spool', 'sewing', 'textile', 'craft supply'],
  }),
  createEmoji({
    id: 'thimble-finger',
    emoji: '�',
    name: 'Hair Pick',
    category: 'accents',
    popularity: 372,
    tags: ['hair pick', 'comb', 'grooming', 'styling tool', 'hair care'],
  }),
  createEmoji({
    id: 'ball-yarn',
    emoji: '🧶',
    name: 'Ball Yarn',
    category: 'accents',
    popularity: 373,
    tags: ['yarn', 'wool ball', 'knitting', 'fiber craft', 'cozy thread'],
  }),
  createEmoji({
    id: 'basket-woven',
    emoji: '🧺',
    name: 'Basket Woven',
    category: 'accents',
    popularity: 374,
    tags: ['basket', 'wicker', 'woven container', 'carry basket', 'storage'],
  }),
  createEmoji({
    id: 'sponge-clean',
    emoji: '🧽',
    name: 'Sponge Clean',
    category: 'accents',
    popularity: 375,
    tags: ['sponge', 'cleaning tool', 'scrubber', 'wash helper', 'absorbent'],
  }),
  createEmoji({
    id: 'soap-bar',
    emoji: '🧼',
    name: 'Soap Bar',
    category: 'accents',
    popularity: 376,
    tags: ['soap', 'cleanser', 'bath bar', 'hygiene', 'wash product'],
  }),
  createEmoji({
    id: 'toothbrush-dental',
    emoji: '🪥',
    name: 'Toothbrush Dental',
    category: 'accents',
    popularity: 377,
    tags: ['toothbrush', 'dental care', 'teeth cleaning', 'hygiene tool', 'brushing'],
  }),
  createEmoji({
    id: 'razor-shave',
    emoji: '🪒',
    name: 'Razor Shave',
    category: 'accents',
    popularity: 378,
    tags: ['razor', 'shaving', 'grooming tool', 'blade', 'personal care'],
  }),
  createEmoji({
    id: 'lotion-bottle',
    emoji: '🧴',
    name: 'Lotion Bottle',
    category: 'accents',
    popularity: 379,
    tags: ['lotion', 'bottle', 'moisturizer', 'skin care', 'pump bottle'],
  }),
  createEmoji({
    id: 'bucket-pail',
    emoji: '�',
    name: 'Bucket Pail',
    category: 'accents',
    popularity: 380,
    tags: ['bucket', 'pail', 'water container', 'carry vessel', 'cleaning tool'],
  }),
  createEmoji({
    id: 'coffin-rest',
    emoji: '⚰️',
    name: 'Coffin Rest',
    category: 'accents',
    popularity: 381,
    tags: ['coffin', 'casket', 'rest place', 'memorial', 'final rest'],
  }),
  createEmoji({
    id: 'headstone-grave',
    emoji: '🪦',
    name: 'Headstone Grave',
    category: 'scenery',
    popularity: 382,
    tags: ['headstone', 'grave', 'tombstone', 'memorial stone', 'resting place'],
  }),
  createEmoji({
    id: 'funeral-urn',
    emoji: '⚱️',
    name: 'Funeral Urn',
    category: 'accents',
    popularity: 383,
    tags: ['urn', 'funeral urn', 'memorial vessel', 'remains holder', 'remembrance'],
  }),
  createEmoji({
    id: 'placard-sign',
    emoji: '🪧',
    name: 'Placard Sign',
    category: 'accents',
    popularity: 384,
    tags: ['placard', 'sign', 'notice board', 'message display', 'announcement'],
  }),
  createEmoji({
    id: 'identification-card',
    emoji: '🪪',
    name: 'Identification Card',
    category: 'accents',
    popularity: 385,
    tags: ['ID card', 'identification', 'badge', 'credential', 'personal card'],
  }),
  createEmoji({
    id: 'diya-lamp',
    emoji: '🪔',
    name: 'Diya Lamp',
    category: 'accents',
    popularity: 386,
    tags: ['diya', 'oil lamp', 'traditional light', 'festival lamp', 'clay lamp'],
  }),
  createEmoji({
    id: 'coin-currency',
    emoji: '🪙',
    name: 'Coin Currency',
    category: 'accents',
    popularity: 387,
    tags: ['coin', 'money', 'currency', 'metal coin', 'payment'],
  }),
  createEmoji({
    id: 'bank-building',
    emoji: '🏦',
    name: 'Bank Building',
    category: 'scenery',
    popularity: 388,
    tags: ['bank', 'financial institution', 'money building', 'vault', 'finance center'],
  }),
  createEmoji({
    id: 'yen-banknote',
    emoji: '💴',
    name: 'Yen Banknote',
    category: 'accents',
    popularity: 389,
    tags: ['yen', 'currency', 'banknote', 'money', 'japanese currency'],
  }),
  createEmoji({
    id: 'dollar-banknote',
    emoji: '💵',
    name: 'Dollar Banknote',
    category: 'accents',
    popularity: 390,
    tags: ['dollar', 'money', 'banknote', 'currency', 'US currency'],
  }),
  createEmoji({
    id: 'euro-banknote',
    emoji: '💶',
    name: 'Euro Banknote',
    category: 'accents',
    popularity: 391,
    tags: ['euro', 'currency', 'banknote', 'money', 'european currency'],
  }),
  createEmoji({
    id: 'pound-banknote',
    emoji: '💷',
    name: 'Pound Banknote',
    category: 'accents',
    popularity: 392,
    tags: ['pound', 'sterling', 'banknote', 'money', 'british currency'],
  }),
  createEmoji({
    id: 'money-wings',
    emoji: '💸',
    name: 'Money Wings',
    category: 'accents',
    popularity: 393,
    tags: ['money flying', 'spending', 'cash loss', 'financial flow', 'expense'],
  }),
  createEmoji({
    id: 'credit-card',
    emoji: '💳',
    name: 'Credit Card',
    category: 'accents',
    popularity: 394,
    tags: ['credit card', 'payment card', 'bank card', 'plastic money', 'transaction'],
  }),
  createEmoji({
    id: 'receipt-bill',
    emoji: '🧾',
    name: 'Receipt Bill',
    category: 'accents',
    popularity: 395,
    tags: ['receipt', 'bill', 'purchase slip', 'transaction record', 'payment proof'],
  }),
  createEmoji({
    id: 'chart-increasing',
    emoji: '📈',
    name: 'Chart Increasing',
    category: 'accents',
    popularity: 396,
    tags: ['chart', 'growth', 'upward trend', 'increasing', 'positive stats'],
  }),
  createEmoji({
    id: 'chart-decreasing',
    emoji: '📉',
    name: 'Chart Decreasing',
    category: 'accents',
    popularity: 397,
    tags: ['chart', 'decline', 'downward trend', 'decreasing', 'negative stats'],
  }),
  createEmoji({
    id: 'bar-chart',
    emoji: '📊',
    name: 'Bar Chart',
    category: 'accents',
    popularity: 398,
    tags: ['bar chart', 'statistics', 'data visualization', 'graph', 'analytics'],
  }),
  createEmoji({
    id: 'clipboard-task',
    emoji: '📋',
    name: 'Clipboard Task',
    category: 'accents',
    popularity: 399,
    tags: ['clipboard', 'task list', 'checklist', 'notes board', 'document holder'],
  }),
  createEmoji({
    id: 'legendary-lettuce',
    emoji: '🥬',
    name: 'Legendary Lettuce',
    category: 'plants',
    popularity: 90,
    priceAnchorPercent: 0.5,
    cost: MAX_EMOJI_COST,
    tags: [
      { keyword: 'lettuce', aliases: ['leafy green', 'garden lettuce', 'salad green'] },
      'signature',
      'garden core',
      'clicker icon',
    ],
  }),
];

const gardenEmojiEntries: EmojiDefinition[] = [
  ...baseGardenEmojiEntries,
];

const sortedByPopularity = [...gardenEmojiEntries].sort((a, b) => a.popularity - b.popularity);
const totalEntries = sortedByPopularity.length;

const pricedByPopularity = sortedByPopularity.map((entry, index) => {
  const anchorPercent = PRICE_ANCHORS[entry.id];
  const percent =
    typeof anchorPercent === 'number'
      ? anchorPercent
      : totalEntries <= 1
      ? 0.5
      : index / (totalEntries - 1);
  return { ...entry, cost: computeBellCurveCost(percent) };
});

const priceMap = new Map(pricedByPopularity.map((entry) => [entry.id, entry.cost]));

export const gardenEmojiCatalog = gardenEmojiEntries.map((entry) => ({
  ...entry,
  cost: priceMap.get(entry.id) ?? computeBellCurveCost(0.5),
}));

const TRILLION = 1_000_000_000_000;
const BILLION = 1_000_000_000;
const MILLION = 1_000_000;

const trimTrailingZeros = (value: number) => {
  const fixed = value.toFixed(2);
  return fixed.replace(/\.0+$/, '').replace(/(\.[1-9])0$/, '$1');
};

export const formatClickValue = (value: number) => {
  if (value >= TRILLION) {
    return `${trimTrailingZeros(value / TRILLION)}T`;
  }

  if (value >= BILLION) {
    return `${trimTrailingZeros(value / BILLION)}B`;
  }

  if (value >= MILLION) {
    return `${trimTrailingZeros(value / MILLION)}M`;
  }

  if (value >= 1000) {
    return value.toLocaleString();
  }

  return `${Math.round(value)}`;
};

export const emojiCategoryOrder: Record<EmojiCategory, number> = {
  plants: 0,
  scenery: 1,
  creatures: 2,
  features: 3,
  accents: 4,
};

