import type { EmojiCategory, EmojiDefinition } from '@/context/GameContext';

export const MIN_EMOJI_COST = 120;
export const MAX_EMOJI_COST = 250_000;

const GAUSSIAN_MEAN = 0.5;
const GAUSSIAN_STD_DEV = 0.18;

const clampPercent = (value: number) => Math.min(Math.max(value, 0), 1);

const gaussianWeight = (percent: number) => {
  const normalized = (clampPercent(percent) - GAUSSIAN_MEAN) / GAUSSIAN_STD_DEV;
  return Math.exp(-0.5 * normalized * normalized);
};

const MIN_WEIGHT = gaussianWeight(0);
const MAX_WEIGHT = gaussianWeight(GAUSSIAN_MEAN);

export const computeBellCurveCost = (percent: number) => {
  const weight = gaussianWeight(percent);
  const span = MAX_WEIGHT - MIN_WEIGHT;
  const normalized = span === 0 ? 0 : (weight - MIN_WEIGHT) / span;
  const cost = MIN_EMOJI_COST + normalized * (MAX_EMOJI_COST - MIN_EMOJI_COST);
  return Math.round(cost);
};

const PRICE_ANCHORS: Record<string, number> = {};

const createEmoji = (
  definition: Omit<EmojiDefinition, 'tags' | 'popularity' | 'cost'> & {
    tags: (string | { keyword: string; aliases?: string[] })[];
    popularity: number;
    cost?: number;
    priceAnchorPercent?: number;
  }
): EmojiDefinition => {
  const normalizedTags = definition.tags.flatMap((entry) => {
    if (typeof entry === 'string') {
      return entry;
    }

    const { keyword, aliases = [] } = entry;
    return [keyword, ...aliases];
  });

  if (typeof definition.priceAnchorPercent === 'number') {
    PRICE_ANCHORS[definition.id] = clampPercent(definition.priceAnchorPercent);
  }

  return {
    id: definition.id,
    emoji: definition.emoji,
    name: definition.name,
    cost: definition.cost ?? MIN_EMOJI_COST,
    category: definition.category,
    tags: Array.from(new Set(normalizedTags)),
    popularity: definition.popularity,
  };
};

const baseGardenEmojiEntries: EmojiDefinition[] = [
  createEmoji({
    id: 'sunflower-bloom',
    emoji: '🌻',
    name: 'Sunflower Bloom',
    cost: 75,
    category: 'plants',
    popularity: 1,
    tags: [
      { keyword: 'sunflower', aliases: ['sunny bloom', 'helios flower', 'yellow flower'] },
      'flower',
      'bright',
      'summer',
      'garden classic',
    ],
  }),
  createEmoji({
    id: 'potted-sprout',
    emoji: '🪴',
    name: 'Potted Sprout',
    cost: 65,
    category: 'plants',
    popularity: 2,
    tags: ['sprout', 'potted plant', 'seedling', 'houseplant', 'clay pot'],
  }),
  createEmoji({
    id: 'hanging-ivy',
    emoji: '🌿',
    name: 'Hanging Ivy',
    cost: 60,
    category: 'plants',
    popularity: 3,
    tags: ['ivy', 'vines', 'greenery', 'trailing plant', 'foliage'],
  }),
  createEmoji({
    id: 'tulip-row',
    emoji: '🌷',
    name: 'Tulip Row',
    cost: 55,
    category: 'plants',
    popularity: 4,
    tags: ['tulip', 'spring flower', 'pink flower', 'garden bed'],
  }),
  createEmoji({
    id: 'wild-mushroom',
    emoji: '🍄',
    name: 'Wild Mushroom',
    cost: 70,
    category: 'plants',
    popularity: 5,
    tags: ['mushroom', 'toadstool', 'forest floor', 'fungi', 'whimsy'],
  }),
  createEmoji({
    id: 'fruit-grove',
    emoji: '🍎',
    name: 'Fruit Grove',
    cost: 68,
    category: 'plants',
    popularity: 6,
    tags: ['apple tree', 'orchard', 'fruit', 'autumn harvest'],
  }),
  createEmoji({
    id: 'desert-cactus',
    emoji: '🌵',
    name: 'Desert Cactus',
    cost: 72,
    category: 'plants',
    popularity: 7,
    tags: ['cactus', 'succulent', 'desert', 'arid garden', 'spines'],
  }),
  createEmoji({
    id: 'evergreen-pine',
    emoji: '🌲',
    name: 'Evergreen Pine',
    cost: 82,
    category: 'plants',
    popularity: 8,
    tags: ['pine', 'evergreen', 'forest tree', 'winter', 'woodland'],
  }),
  createEmoji({
    id: 'golden-sunrise',
    emoji: '🌅',
    name: 'Golden Sunrise',
    cost: 112,
    category: 'scenery',
    popularity: 9,
    tags: ['sunrise', 'morning sky', 'sunrise horizon', 'warm light'],
  }),
  createEmoji({
    id: 'midday-sun',
    emoji: '🌞',
    name: 'Midday Sun',
    cost: 124,
    category: 'scenery',
    popularity: 10,
    tags: ['sun', 'sunlight', 'bright sky', 'daytime', 'solar'],
  }),
  createEmoji({
    id: 'rainbow-arc',
    emoji: '🌈',
    name: 'Rainbow Arc',
    cost: 135,
    category: 'scenery',
    popularity: 11,
    tags: ['rainbow', 'colorful sky', 'after rain', 'magic light'],
  }),
  createEmoji({
    id: 'soft-clouds',
    emoji: '🌤️',
    name: 'Soft Clouds',
    cost: 104,
    category: 'scenery',
    popularity: 12,
    tags: ['clouds', 'partly sunny', 'breeze', 'gentle weather'],
  }),
  createEmoji({
    id: 'twilight-moon',
    emoji: '🌙',
    name: 'Twilight Moon',
    cost: 130,
    category: 'scenery',
    popularity: 13,
    tags: ['moon', 'night sky', 'evening', 'calm', 'glow'],
  }),
  createEmoji({
    id: 'shooting-star-trail',
    emoji: '🌠',
    name: 'Shooting Star Trail',
    cost: 142,
    category: 'scenery',
    popularity: 14,
    tags: ['shooting star', 'wish', 'night sparkle', 'meteor'],
  }),
  createEmoji({
    id: 'spring-rain',
    emoji: '🌧️',
    name: 'Spring Rain',
    cost: 110,
    category: 'scenery',
    popularity: 15,
    tags: ['rain', 'shower', 'storm', 'water', 'refresh'],
  }),
  createEmoji({
    id: 'garden-firefly',
    emoji: '🪄',
    name: 'Garden Firefly Glow',
    cost: 108,
    category: 'accents',
    popularity: 16,
    tags: ['firefly', 'sparkle', 'wand light', 'magic glow', 'tiny lights'],
  }),
  createEmoji({
    id: 'honeybee-buzz',
    emoji: '🐝',
    name: 'Honeybee Buzz',
    cost: 78,
    category: 'creatures',
    popularity: 17,
    tags: ['bee', 'pollinator', 'buzz', 'striped insect', 'honey'],
  }),
  createEmoji({
    id: 'monarch-butterfly',
    emoji: '🦋',
    name: 'Monarch Butterfly',
    cost: 82,
    category: 'creatures',
    popularity: 18,
    tags: ['butterfly', 'wings', 'flutter', 'orange butterfly', 'pollinator'],
  }),
  createEmoji({
    id: 'ladybug-luck',
    emoji: '🐞',
    name: 'Ladybug Luck',
    cost: 76,
    category: 'creatures',
    popularity: 19,
    tags: ['ladybug', 'ladybird', 'spots', 'garden insect'],
  }),
  createEmoji({
    id: 'songbird-perch',
    emoji: '🐦',
    name: 'Songbird Perch',
    cost: 84,
    category: 'creatures',
    popularity: 20,
    tags: ['bird', 'songbird', 'perched bird', 'tweet'],
  }),
  createEmoji({
    id: 'field-bunny',
    emoji: '🐇',
    name: 'Field Bunny',
    cost: 88,
    category: 'creatures',
    popularity: 21,
    tags: ['bunny', 'rabbit', 'hare', 'spring critter'],
  }),
  createEmoji({
    id: 'garden-tortoise',
    emoji: '🐢',
    name: 'Garden Tortoise',
    cost: 86,
    category: 'creatures',
    popularity: 22,
    tags: ['turtle', 'tortoise', 'slow friend', 'shell'],
  }),
  createEmoji({
    id: 'curious-cat',
    emoji: '🐈',
    name: 'Curious Garden Cat',
    cost: 94,
    category: 'creatures',
    popularity: 23,
    tags: ['cat', 'kitty', 'pet', 'feline', 'garden companion'],
  }),
  createEmoji({
    id: 'cozy-picnic',
    emoji: '🧺',
    name: 'Cozy Picnic Basket',
    cost: 98,
    category: 'features',
    popularity: 24,
    tags: ['picnic', 'basket', 'blanket', 'snacks', 'outing'],
  }),
  createEmoji({
    id: 'garden-lantern',
    emoji: '🏮',
    name: 'Garden Lantern',
    cost: 96,
    category: 'features',
    popularity: 25,
    tags: ['lantern', 'hanging light', 'glow', 'evening lighting'],
  }),
  createEmoji({
    id: 'stone-path',
    emoji: '🧱',
    name: 'Brick Garden Path',
    cost: 90,
    category: 'features',
    popularity: 26,
    tags: ['brick path', 'garden walkway', 'stonework', 'pathway', 'patterned steps'],
  }),
  createEmoji({
    id: 'garden-fountain',
    emoji: '⛲',
    name: 'Garden Fountain',
    cost: 148,
    category: 'features',
    popularity: 27,
    tags: ['fountain', 'water feature', 'splash', 'centerpiece'],
  }),
  createEmoji({
    id: 'greenhouse-nook',
    emoji: '🏡',
    name: 'Greenhouse Nook',
    cost: 185,
    category: 'features',
    popularity: 28,
    tags: ['greenhouse', 'garden home', 'glass house', 'cozy corner'],
  }),
  createEmoji({
    id: 'wooden-bench',
    emoji: '🪑',
    name: 'Wooden Garden Bench',
    cost: 132,
    category: 'features',
    popularity: 29,
    tags: ['bench', 'seat', 'rest spot', 'gather'],
  }),
  createEmoji({
    id: 'herbal-bouquet',
    emoji: '💐',
    name: 'Herbal Bouquet',
    cost: 102,
    category: 'accents',
    popularity: 30,
    tags: ['bouquet', 'flowers', 'arrangement', 'celebration'],
  }),
  createEmoji({
    id: 'glittering-lights',
    emoji: '✨',
    name: 'Glittering Lights',
    cost: 114,
    category: 'accents',
    popularity: 31,
    tags: ['sparkle', 'twinkle', 'stars', 'fairy lights'],
  }),
  createEmoji({
    id: 'garden-heart',
    emoji: '💚',
    name: 'Garden Heart Glow',
    cost: 110,
    category: 'accents',
    popularity: 32,
    tags: ['heart', 'green heart', 'love', 'care'],
  }),
  createEmoji({
    id: 'campfire-cozy',
    emoji: '🔥',
    name: 'Campfire Cozy',
    cost: 152,
    category: 'features',
    popularity: 33,
    tags: ['fire', 'campfire', 'warmth', 'gather'],
  }),
  createEmoji({
    id: 'dawn-dew',
    emoji: '💧',
    name: 'Dawn Dew Drop',
    cost: 99,
    category: 'accents',
    popularity: 34,
    tags: ['water drop', 'dew', 'refreshing', 'morning'],
  }),
  createEmoji({
    id: 'garden-rainbow-flower',
    emoji: '🌼',
    name: 'Garden Daisy',
    cost: 90,
    category: 'plants',
    popularity: 35,
    tags: ['daisy', 'wildflower', 'yellow bloom', 'sunny'],
  }),
  createEmoji({
    id: 'wind-swirls',
    emoji: '💨',
    name: 'Whistling Wind Swirls',
    cost: 104,
    category: 'accents',
    popularity: 36,
    tags: ['wind', 'gust', 'breeze', 'movement'],
  }),
  createEmoji({
    id: 'glowing-star',
    emoji: '🌟',
    name: 'Glowing Star',
    cost: 128,
    category: 'accents',
    popularity: 37,
    tags: ['star', 'shine', 'highlight', 'night sparkle'],
  }),
  createEmoji({
    id: 'tiny-sprouts',
    emoji: '🌱',
    name: 'Tiny Sprouts',
    cost: 82,
    category: 'plants',
    popularity: 38,
    tags: ['sprout', 'seedling', 'new growth', 'fresh'],
  }),
  createEmoji({
    id: 'lily-pad-pond',
    emoji: '🪷',
    name: 'Lily Pad Pond',
    cost: 150,
    category: 'features',
    popularity: 39,
    tags: ['lotus', 'pond', 'water garden', 'tranquil'],
  }),
  createEmoji({
    id: 'lavender-lane',
    emoji: '🪻',
    name: 'Lavender Lane',
    category: 'plants',
    popularity: 40,
    tags: ['lavender', 'purple flowers', 'fragrance', 'calming bloom', 'herbal'],
  }),
  createEmoji({
    id: 'bonsai-retreat',
    emoji: '🎍',
    name: 'Bonsai Retreat',
    category: 'plants',
    popularity: 41,
    tags: ['bonsai', 'mini tree', 'zen garden', 'trimmed branches', 'careful pruning'],
  }),
  createEmoji({
    id: 'autumn-maple-grove',
    emoji: '🍁',
    name: 'Maple Leaf',
    category: 'scenery',
    popularity: 42,
    tags: ['maple', 'fall leaves', 'crimson canopy', 'seasonal color', 'foliage'],
  }),
  createEmoji({
    id: 'morning-mist-drift',
    emoji: '🌫️',
    name: 'Morning Mist Drift',
    category: 'scenery',
    popularity: 43,
    tags: ['mist', 'fog', 'soft haze', 'cool dawn', 'breeze'],
  }),
  createEmoji({
    id: 'gentle-hedgehog',
    emoji: '🦔',
    name: 'Gentle Hedgehog',
    category: 'creatures',
    popularity: 44,
    tags: ['hedgehog', 'garden friend', 'spines', 'nocturnal', 'critter'],
  }),
  createEmoji({
    id: 'midnight-owl-roost',
    emoji: '🦉',
    name: 'Midnight Owl Roost',
    category: 'creatures',
    popularity: 45,
    tags: ['owl', 'night watch', 'wisdom', 'perch', 'stars'],
  }),
  createEmoji({
    id: 'sage-teahouse',
    emoji: '🍵',
    name: 'Sage Teahouse',
    category: 'features',
    popularity: 46,
    tags: ['tea', 'tea house', 'calm retreat', 'warm cup', 'gather'],
  }),
  createEmoji({
    id: 'stone-arch-bridge',
    emoji: '🌉',
    name: 'Stone Arch Bridge',
    category: 'features',
    popularity: 47,
    tags: ['bridge', 'archway', 'garden path', 'walkover', 'water crossing'],
  }),
  createEmoji({
    id: 'twilight-wind-chimes',
    emoji: '🎐',
    name: 'Twilight Wind Chimes',
    category: 'accents',
    popularity: 48,
    tags: ['wind chime', 'gentle sound', 'breeze song', 'evening accent', 'hanging charm'],
  }),
  createEmoji({
    id: 'glimmer-orb-lights',
    emoji: '🔮',
    name: 'Glimmer Orb Lights',
    category: 'accents',
    popularity: 49,
    tags: ['orb', 'mystic glow', 'path lights', 'floating light', 'spark'],
  }),
  createEmoji({
    id: 'pocket-crickets',
    emoji: '🦗',
    name: 'Pocket Crickets',
    category: 'creatures',
    popularity: 50,
    tags: ['cricket', 'evening song', 'chirp', 'nighttime', 'garden sound'],
  }),
  createEmoji({
    id: 'cobblestone-gate',
    emoji: '🚪',
    name: 'Cobblestone Gate',
    category: 'features',
    popularity: 51,
    tags: ['garden gate', 'entryway', 'stonework', 'welcome arch', 'entrance'],
  }),
  createEmoji({
    id: 'evergreen-oak',
    emoji: '🌳',
    name: 'Evergreen Oak',
    category: 'plants',
    popularity: 52,
    tags: ['oak tree', 'canopy shade', 'stately tree', 'garden landmark', 'evergreen'],
  }),
  createEmoji({
    id: 'rose-archway',
    emoji: '🌹',
    name: 'Rose Archway',
    category: 'plants',
    popularity: 53,
    tags: ['rose arch', 'climbing roses', 'garden entrance', 'petals', 'romantic walkway'],
  }),
  createEmoji({
    id: 'sakura-breeze',
    emoji: '🌸',
    name: 'Sakura Breeze',
    category: 'plants',
    popularity: 54,
    tags: ['cherry blossom', 'sakura', 'pink petals', 'spring bloom', 'hanami'],
  }),
  createEmoji({
    id: 'hibiscus-halo',
    emoji: '🌺',
    name: 'Hibiscus Halo',
    category: 'plants',
    popularity: 55,
    tags: ['hibiscus', 'tropical bloom', 'bold petals', 'vibrant flower', 'island garden'],
  }),
  createEmoji({
    id: 'strawberry-patch',
    emoji: '🍓',
    name: 'Strawberry Patch',
    category: 'plants',
    popularity: 56,
    tags: ['strawberry', 'berry patch', 'sweet harvest', 'garden fruit', 'red berries'],
  }),
  createEmoji({
    id: 'melon-vine',
    emoji: '🍈',
    name: 'Melon Vine',
    category: 'plants',
    popularity: 57,
    tags: ['melon', 'creeping vine', 'green melon', 'summer harvest', 'garden fruit'],
  }),
  createEmoji({
    id: 'blueberry-bramble',
    emoji: '🫐',
    name: 'Blueberry Bramble',
    category: 'plants',
    popularity: 58,
    tags: ['blueberry', 'wild berry', 'purple fruit', 'garden bush', 'sweet harvest'],
  }),
  createEmoji({
    id: 'swan-lagoon',
    emoji: '🦢',
    name: 'Swan Lagoon',
    category: 'creatures',
    popularity: 59,
    tags: ['swan', 'calm water', 'graceful bird', 'lagoon', 'pond life'],
  }),
  createEmoji({
    id: 'peacock-parade',
    emoji: '🦚',
    name: 'Peacock Parade',
    category: 'creatures',
    popularity: 60,
    tags: ['peacock', 'feather fan', 'vibrant bird', 'garden parade', 'plumage'],
  }),
  createEmoji({
    id: 'garden-flamingo',
    emoji: '🦩',
    name: 'Garden Flamingo',
    category: 'creatures',
    popularity: 61,
    tags: ['flamingo', 'garden bird', 'pink bird', 'lawn art', 'tropical wader'],
  }),
  createEmoji({
    id: 'foxtail-hollow',
    emoji: '🦊',
    name: 'Foxtail Hollow',
    category: 'creatures',
    popularity: 62,
    tags: ['fox', 'forest friend', 'clever critter', 'bushy tail', 'garden visitor'],
  }),
  createEmoji({
    id: 'river-otter',
    emoji: '🦦',
    name: 'River Otter',
    category: 'creatures',
    popularity: 63,
    tags: ['otter', 'riverbank', 'playful swimmer', 'freshwater friend', 'whiskers'],
  }),
  createEmoji({
    id: 'winged-companion',
    emoji: '🪽',
    name: 'Winged Companion',
    category: 'accents',
    popularity: 64,
    tags: ['wing', 'feather', 'flutter', 'airborne', 'light breeze'],
  }),
  createEmoji({
    id: 'lantern-glow',
    emoji: '🪔',
    name: 'Lantern Glow Diya',
    category: 'accents',
    popularity: 65,
    tags: ['oil lamp', 'festival glow', 'warm flame', 'evening light', 'diya lantern'],
  }),
  createEmoji({
    id: 'picnic-basket',
    emoji: '🥪',
    name: 'Picnic Sandwich Stack',
    category: 'features',
    popularity: 66,
    tags: ['sandwich', 'packed lunch', 'picnic basket', 'layered bites', 'outdoor meal'],
  }),
  createEmoji({
    id: 'watering-pail',
    emoji: '🪣',
    name: 'Watering Pail',
    category: 'features',
    popularity: 67,
    tags: ['watering can', 'garden tool', 'sprinkle', 'metal pail', 'garden care'],
  }),
  createEmoji({
    id: 'mossy-log',
    emoji: '🪵',
    name: 'Mossy Log',
    category: 'features',
    popularity: 68,
    tags: ['mossy log', 'forest floor', 'wooden log', 'soft moss', 'natural seat'],
  }),
  createEmoji({
    id: 'riverstone-stack',
    emoji: '🪨',
    name: 'Riverstone Stack',
    category: 'features',
    popularity: 69,
    tags: ['river stone', 'zen rocks', 'stacked stones', 'garden cairn', 'smooth pebbles'],
  }),
  createEmoji({
    id: 'empty-nest-perch',
    emoji: '🪹',
    name: 'Empty Nest Perch',
    category: 'features',
    popularity: 70,
    tags: ['empty nest', 'twigs', 'perch', 'tree branch', 'quiet rest'],
  }),
  createEmoji({
    id: 'cozy-nest-eggs',
    emoji: '🪺',
    name: 'Cozy Nest Eggs',
    category: 'features',
    popularity: 71,
    tags: ['nest eggs', 'blue eggs', 'twig nest', 'springtime', 'gentle care'],
  }),
  createEmoji({
    id: 'ginger-root-bundle',
    emoji: '🫚',
    name: 'Ginger Root Bundle',
    category: 'plants',
    popularity: 72,
    tags: ['ginger root', 'spice', 'warmth', 'herbal', 'market bundle'],
  }),
  createEmoji({
    id: 'garden-pea-pod',
    emoji: '🫛',
    name: 'Garden Pea Pod',
    category: 'plants',
    popularity: 73,
    tags: ['pea pod', 'peas', 'fresh greens', 'snap pea', 'climbing vine'],
  }),
  createEmoji({
    id: 'garlic-bulb-cluster',
    emoji: '🧄',
    name: 'Garlic Bulb Cluster',
    category: 'plants',
    popularity: 74,
    tags: ['garlic bulb', 'kitchen garden', 'aroma', 'culinary', 'clove bundle'],
  }),
  createEmoji({
    id: 'stone-flatbread-platter',
    emoji: '🫓',
    name: 'Stone Flatbread Platter',
    category: 'features',
    popularity: 75,
    tags: ['flatbread', 'warm loaf', 'hearth', 'artisan bake', 'shared snack'],
  }),
  createEmoji({
    id: 'fireside-fondue',
    emoji: '🫕',
    name: 'Fireside Fondue',
    category: 'features',
    popularity: 76,
    tags: ['fondue pot', 'cozy treat', 'evening glow', 'shared bites', 'golden cheese'],
  }),
  createEmoji({
    id: 'sunlit-preserve-jar',
    emoji: '🫙',
    name: 'Sunlit Preserve Jar',
    category: 'features',
    popularity: 77,
    tags: ['glass jar', 'homemade jam', 'summer fruit', 'pantry shelf', 'sweet spread'],
  }),
  createEmoji({
    id: 'meadow-cupcake-stand',
    emoji: '🧁',
    name: 'Meadow Cupcake Stand',
    category: 'accents',
    popularity: 78,
    tags: ['cupcake', 'pastel frosting', 'garden party', 'sweet treat', 'dessert stand'],
  }),
  createEmoji({
    id: 'cookie-platter',
    emoji: '🍪',
    name: 'Cookie Platter',
    category: 'accents',
    popularity: 79,
    tags: ['cookie', 'fresh baked', 'comfort snack', 'chocolate chip', 'afternoon tea'],
  }),
  createEmoji({
    id: 'harvest-hand-pie',
    emoji: '🥧',
    name: 'Harvest Hand Pie',
    category: 'accents',
    popularity: 80,
    tags: ['pie', 'autumn dessert', 'cinnamon spice', 'homestead treat', 'golden crust'],
  }),
  createEmoji({
    id: 'sparkling-juice-carton',
    emoji: '🧃',
    name: 'Sparkling Juice Carton',
    category: 'accents',
    popularity: 81,
    tags: ['juice box', 'refreshing sip', 'fruit drink', 'picnic cooler', 'hydration'],
  }),
  createEmoji({
    id: 'frosted-ice-gems',
    emoji: '🧊',
    name: 'Frosted Ice Gems',
    category: 'accents',
    popularity: 82,
    tags: ['ice cube', 'cool breeze', 'frost sparkle', 'chill station', 'glass clink'],
  }),
  createEmoji({
    id: 'bubble-tea-cart',
    emoji: '🧋',
    name: 'Bubble Tea Cart',
    category: 'features',
    popularity: 83,
    tags: ['bubble tea', 'tapioca pearls', 'tea stand', 'garden cafe', 'sweet sip'],
  }),
  createEmoji({
    id: 'mate-garden-gourd',
    emoji: '🧉',
    name: 'Mate Garden Gourd',
    category: 'features',
    popularity: 84,
    tags: ['mate gourd', 'shared drink', 'herbal infusion', 'cozy gathering', 'metal straw'],
  }),
  createEmoji({
    id: 'sky-dancing-kite',
    emoji: '🪁',
    name: 'Sky Dancing Kite',
    category: 'scenery',
    popularity: 85,
    tags: ['kite', 'breezy day', 'string trail', 'playful sky', 'spring outing'],
  }),
  createEmoji({
    id: 'garden-lounge-sofa',
    emoji: '🛋️',
    name: 'Garden Lounge Sofa',
    category: 'features',
    popularity: 86,
    tags: ['sofa', 'outdoor lounge', 'cushions', 'relax corner', 'sunset seating'],
  }),
  createEmoji({
    id: 'playful-park-slide',
    emoji: '🛝',
    name: 'Playful Park Slide',
    category: 'features',
    popularity: 87,
    tags: ['slide', 'playground', 'family fun', 'park feature', 'joyful swoop'],
  }),
  createEmoji({
    id: 'lucky-garden-coin',
    emoji: '🪙',
    name: 'Lucky Garden Coin',
    category: 'accents',
    popularity: 88,
    tags: ['coin', 'lucky charm', 'gleaming gold', 'wish token', 'hidden treasure'],
  }),
  createEmoji({
    id: 'nazar-sun-catcher',
    emoji: '🧿',
    name: 'Nazar Sun Catcher',
    category: 'accents',
    popularity: 89,
    tags: ['nazar charm', 'protective talisman', 'window glimmer', 'blue glass', 'sun catcher'],
  }),
  createEmoji({
    id: 'tidepool-coral-cluster',
    emoji: '🪸',
    name: 'Tidepool Coral Cluster',
    category: 'scenery',
    popularity: 91,
    tags: ['coral', 'tidepool', 'marine garden', 'coastal color', 'undersea life'],
  }),
  createEmoji({
    id: 'story-nesting-dolls',
    emoji: '🪆',
    name: 'Story Nesting Dolls',
    category: 'accents',
    popularity: 92,
    tags: ['nesting dolls', 'painted keepsake', 'folk art', 'layered surprise', 'display shelf'],
  }),
  createEmoji({
    id: 'citrus-sunburst-grove',
    emoji: '🍊',
    name: 'Citrus Sunburst Grove',
    category: 'plants',
    popularity: 93,
    tags: ['orange grove', 'citrus', 'sunny fruit', 'scented blossom', 'bright canopy'],
  }),
  createEmoji({
    id: 'lemontwist-orchard',
    emoji: '🍋',
    name: 'Lemontwist Orchard',
    category: 'plants',
    popularity: 94,
    tags: ['lemon tree', 'zesty fruit', 'citrus grove', 'yellow bloom', 'fresh zest'],
  }),
  createEmoji({
    id: 'vineyard-trellis-cluster',
    emoji: '🍇',
    name: 'Vineyard Trellis Cluster',
    category: 'plants',
    popularity: 95,
    tags: ['grapes', 'vineyard', 'trellis vines', 'clustered fruit', 'late harvest'],
  }),
  createEmoji({
    id: 'river-melon-patch',
    emoji: '🍉',
    name: 'River Melon Patch',
    category: 'plants',
    popularity: 96,
    tags: ['watermelon', 'summer fruit', 'striped rind', 'picnic harvest', 'juicy patch'],
  }),
  createEmoji({
    id: 'scarlet-cherry-twins',
    emoji: '🍒',
    name: 'Scarlet Cherry Twins',
    category: 'plants',
    popularity: 97,
    tags: ['cherries', 'pair of fruit', 'sweet orchard', 'blossom stem', 'juicy duo'],
  }),
  createEmoji({
    id: 'velvet-peach-canopy',
    emoji: '🍑',
    name: 'Velvet Peach Canopy',
    category: 'plants',
    popularity: 98,
    tags: ['peach', 'summer orchard', 'fuzzy fruit', 'blush petals', 'sunset grove'],
  }),
  createEmoji({
    id: 'pineapple-lantern-ridge',
    emoji: '🍍',
    name: 'Pineapple Lantern Ridge',
    category: 'plants',
    popularity: 99,
    tags: ['pineapple', 'tropical fruit', 'spiky crown', 'golden harvest', 'sunny slope'],
  }),
  createEmoji({
    id: 'island-coconut-canopy',
    emoji: '🥥',
    name: 'Island Coconut Canopy',
    category: 'plants',
    popularity: 100,
    tags: ['coconut', 'palm cluster', 'tropical shade', 'shell husk', 'island breeze'],
  }),
  createEmoji({
    id: 'kiwi-trellis-drift',
    emoji: '🥝',
    name: 'Kiwi Trellis Drift',
    category: 'plants',
    popularity: 101,
    tags: ['kiwi', 'vine fruit', 'emerald slices', 'garden pergola', 'tartan rind'],
  }),
  createEmoji({
    id: 'mango-gold-grove',
    emoji: '🥭',
    name: 'Mango Gold Grove',
    category: 'plants',
    popularity: 102,
    tags: ['mango', 'tropical orchard', 'sunny fruit', 'sweet nectar', 'golden branch'],
  }),
  createEmoji({
    id: 'heritage-tomato-vine',
    emoji: '🍅',
    name: 'Heritage Tomato Vine',
    category: 'plants',
    popularity: 103,
    tags: ['tomato', 'garden patch', 'vine ripened', 'ruby fruit', 'heirloom produce'],
  }),
  createEmoji({
    id: 'midnight-eggplant-row',
    emoji: '🍆',
    name: 'Midnight Eggplant Row',
    category: 'plants',
    popularity: 104,
    tags: ['eggplant', 'nightshade', 'deep purple', 'row planting', 'gleaming skin'],
  }),
  createEmoji({
    id: 'broccoli-forest-floret',
    emoji: '🥦',
    name: 'Broccoli Forest Floret',
    category: 'plants',
    popularity: 105,
    tags: ['broccoli', 'floret cluster', 'crunchy green', 'veggie patch', 'garden harvest'],
  }),
  createEmoji({
    id: 'cool-cucumber-tangle',
    emoji: '🥒',
    name: 'Cool Cucumber Tangle',
    category: 'plants',
    popularity: 106,
    tags: ['cucumber', 'vine', 'refreshing crunch', 'garden trellis', 'emerald spiral'],
  }),
  createEmoji({
    id: 'cornfield-sunrise-stalks',
    emoji: '🌽',
    name: 'Cornfield Sunrise Stalks',
    category: 'plants',
    popularity: 107,
    tags: ['corn', 'maize', 'tall stalks', 'golden tassel', 'farm row'],
  }),
  createEmoji({
    id: 'carrot-top-bundle',
    emoji: '🥕',
    name: 'Carrot Top Bundle',
    category: 'plants',
    popularity: 108,
    tags: ['carrot', 'root vegetable', 'orange harvest', 'garden bed', 'crisp crunch'],
  }),
  createEmoji({
    id: 'amber-sweet-potato-hill',
    emoji: '🍠',
    name: 'Amber Sweet Potato Hill',
    category: 'plants',
    popularity: 109,
    tags: ['sweet potato', 'root patch', 'baked aroma', 'autumn plot', 'earthy harvest'],
  }),
  createEmoji({
    id: 'starlit-bean-vines',
    emoji: '🫘',
    name: 'Starlit Bean Vines',
    category: 'plants',
    popularity: 110,
    tags: ['beans', 'climbing vine', 'night bloom', 'protein pods', 'garden lattice'],
  }),
  createEmoji({
    id: 'mountain-dawn-crest',
    emoji: '🌄',
    name: 'Mountain Dawn Crest',
    category: 'scenery',
    popularity: 111,
    tags: ['sunrise', 'mountain range', 'orange horizon', 'travel view', 'alpine glow'],
  }),
  createEmoji({
    id: 'sunset-ridge-horizon',
    emoji: '🌇',
    name: 'Sunset Ridge Horizon',
    category: 'scenery',
    popularity: 112,
    tags: ['sunset', 'city silhouette', 'glowing skyline', 'evening light', 'twilight sky'],
  }),
  createEmoji({
    id: 'twilight-metro-aurora',
    emoji: '🌆',
    name: 'Twilight Metro Aurora',
    category: 'scenery',
    popularity: 113,
    tags: ['cityscape', 'violet dusk', 'windows aglow', 'urban evening', 'skyline'],
  }),
  createEmoji({
    id: 'starlit-promenade',
    emoji: '🌃',
    name: 'Starlit Promenade',
    category: 'scenery',
    popularity: 114,
    tags: ['night city', 'stars', 'evening walk', 'glittering lights', 'urban sky'],
  }),
  createEmoji({
    id: 'galaxy-overlook',
    emoji: '🌌',
    name: 'Galaxy Overlook',
    category: 'scenery',
    popularity: 115,
    tags: ['milky way', 'night sky', 'cosmic swirl', 'stargazing', 'midnight view'],
  }),
  createEmoji({
    id: 'ember-volcano-crest',
    emoji: '🌋',
    name: 'Ember Volcano Crest',
    category: 'scenery',
    popularity: 116,
    tags: ['volcano', 'lava glow', 'smoke plume', 'island peak', 'fiery mountain'],
  }),
  createEmoji({
    id: 'snowcap-summit-trail',
    emoji: '🏔️',
    name: 'Snowcap Summit Trail',
    category: 'scenery',
    popularity: 117,
    tags: ['mountain', 'snow peak', 'alpine trail', 'crisp air', 'hiking path'],
  }),
  createEmoji({
    id: 'wanderer-campfire-cove',
    emoji: '🏕️',
    name: 'Wanderer Campfire Cove',
    category: 'scenery',
    popularity: 118,
    tags: ['campground', 'tent', 'stars above', 'night retreat', 'bonfire glow'],
  }),
  createEmoji({
    id: 'parasol-shoreline',
    emoji: '🏖️',
    name: 'Parasol Shoreline',
    category: 'scenery',
    popularity: 119,
    tags: ['beach', 'umbrella', 'coastal sand', 'waves', 'holiday rest'],
  }),
  createEmoji({
    id: 'lagoon-island-haven',
    emoji: '🏝️',
    name: 'Lagoon Island Haven',
    category: 'scenery',
    popularity: 120,
    tags: ['island', 'tropical', 'solitude', 'palm beach', 'turquoise water'],
  }),
  createEmoji({
    id: 'pondside-frog-chorus',
    emoji: '🐸',
    name: 'Pondside Frog Chorus',
    category: 'creatures',
    popularity: 121,
    tags: ['frog', 'lily pad singer', 'rainy day', 'croak melody', 'pond friend'],
  }),
  createEmoji({
    id: 'mossy-snail-trail',
    emoji: '🐌',
    name: 'Mossy Snail Trail',
    category: 'creatures',
    popularity: 122,
    tags: ['snail', 'slow wanderer', 'spiral shell', 'morning dew', 'garden crawler'],
  }),
  createEmoji({
    id: 'acorn-chipmunk-dash',
    emoji: '🐿️',
    name: 'Acorn Chipmunk Dash',
    category: 'creatures',
    popularity: 123,
    tags: ['chipmunk', 'acorn gatherer', 'striped tail', 'burrow friend', 'quick scurry'],
  }),
  createEmoji({
    id: 'garden-reef-octopus',
    emoji: '🐙',
    name: 'Garden Reef Octopus',
    category: 'creatures',
    popularity: 124,
    tags: ['octopus', 'tidal pool', 'shifting colors', 'curious tentacles', 'ocean visitor'],
  }),
  createEmoji({
    id: 'koi-glassfish',
    emoji: '🐠',
    name: 'Koi Glassfish',
    category: 'creatures',
    popularity: 125,
    tags: ['fish', 'koi pond', 'glimmer scales', 'tranquil swim', 'water companion'],
  }),
  createEmoji({
    id: 'puffer-lagoon-guest',
    emoji: '🐡',
    name: 'Puffer Lagoon Guest',
    category: 'creatures',
    popularity: 126,
    tags: ['pufferfish', 'puffball fish', 'coastal reef', 'playful float', 'spiny friend'],
  }),
  createEmoji({
    id: 'sunrise-dolphin-leap',
    emoji: '🐬',
    name: 'Sunrise Dolphin Leap',
    category: 'creatures',
    popularity: 127,
    tags: ['dolphin', 'ocean jump', 'wave arc', 'friendly marine', 'sparkling spray'],
  }),
  createEmoji({
    id: 'whale-song-drift',
    emoji: '🐳',
    name: 'Whale Song Drift',
    category: 'creatures',
    popularity: 128,
    tags: ['whale', 'deep sea', 'gentle giant', 'ocean current', 'soothing call'],
  }),
  createEmoji({
    id: 'reef-shark-glide',
    emoji: '🦈',
    name: 'Reef Shark Glide',
    category: 'creatures',
    popularity: 129,
    tags: ['shark', 'sleek fin', 'blue water', 'coastal guardian', 'swift swim'],
  }),
  createEmoji({
    id: 'harbor-lobster-nook',
    emoji: '🦞',
    name: 'Harbor Lobster Nook',
    category: 'creatures',
    popularity: 130,
    tags: ['lobster', 'tidal catch', 'rocky inlet', 'seafood dock', 'crimson shell'],
  }),
  createEmoji({
    id: 'lagoon-canoe-launch',
    emoji: '🛶',
    name: 'Lagoon Canoe Launch',
    category: 'features',
    popularity: 131,
    tags: ['canoe', 'dock', 'paddle adventure', 'lake outing', 'wood pier'],
  }),
  createEmoji({
    id: 'palm-hut-hideaway',
    emoji: '🛖',
    name: 'Palm Hut Hideaway',
    category: 'features',
    popularity: 132,
    tags: ['hut', 'thatch roof', 'tropical rest', 'shaded shelter', 'breeze break'],
  }),
  createEmoji({
    id: 'garden-shrine-pavilion',
    emoji: '🛕',
    name: 'Garden Shrine Pavilion',
    category: 'features',
    popularity: 133,
    tags: ['temple', 'meditation', 'ornate arch', 'quiet refuge', 'lantern glow'],
  }),
  createEmoji({
    id: 'greenhouse-window-arch',
    emoji: '🪟',
    name: 'Greenhouse Window Arch',
    category: 'features',
    popularity: 134,
    tags: ['glass window', 'sunlight beam', 'plant house', 'framed view', 'paned arch'],
  }),
  createEmoji({
    id: 'reflective-garden-mirror',
    emoji: '🪞',
    name: 'Reflective Garden Mirror',
    category: 'features',
    popularity: 135,
    tags: ['mirror', 'shimmer frame', 'light bounce', 'illusion depth', 'ornament'],
  }),
  createEmoji({
    id: 'outdoor-soaking-tub',
    emoji: '🛁',
    name: 'Outdoor Soaking Tub',
    category: 'features',
    popularity: 136,
    tags: ['bathtub', 'spa retreat', 'steam soak', 'garden bath', 'relax station'],
  }),
  createEmoji({
    id: 'sparkler-sky-burst',
    emoji: '🎇',
    name: 'Sparkler Sky Burst',
    category: 'accents',
    popularity: 137,
    tags: ['sparkler', 'festive light', 'night sparkle', 'celebration flare', 'glitter arcs'],
  }),
  createEmoji({
    id: 'firework-bloom-finale',
    emoji: '🎆',
    name: 'Firework Bloom Finale',
    category: 'accents',
    popularity: 138,
    tags: ['fireworks', 'festival sky', 'bright bloom', 'night show', 'celebration'],
  }),
  createEmoji({
    id: 'ribbon-balloon-cluster',
    emoji: '🎈',
    name: 'Ribbon Balloon Cluster',
    category: 'accents',
    popularity: 139,
    tags: ['balloon', 'party float', 'color pop', 'garden gala', 'festive accent'],
  }),
  createEmoji({
    id: 'confetti-cannon-spritz',
    emoji: '🎉',
    name: 'Confetti Cannon Spritz',
    category: 'accents',
    popularity: 140,
    tags: ['party popper', 'celebration confetti', 'bursting streamers', 'joyful cheer', 'festive sparkle'],
  }),
  createEmoji({
    id: 'lantern-candle-nook',
    emoji: '🕯️',
    name: 'Lantern Candle Nook',
    category: 'accents',
    popularity: 141,
    tags: ['candle', 'warm glow', 'evening ambiance', 'soft light', 'flicker flame'],
  }),
  createEmoji({
    id: 'idea-lantern-bulb',
    emoji: '💡',
    name: 'Idea Lantern Bulb',
    category: 'accents',
    popularity: 142,
    tags: ['lightbulb', 'bright idea', 'illumination', 'glowing accent', 'spark of light'],
  }),
  createEmoji({
    id: 'sunset-roadster-lineup',
    emoji: '🚗',
    name: 'Sunset Roadster Lineup',
    category: 'features',
    popularity: 143,
    tags: ['car', 'convertible', 'sunset cruise', 'chrome shine', 'garden showcase'],
  }),
  createEmoji({
    id: 'vintage-wagon-pull-in',
    emoji: '🚙',
    name: 'Vintage Wagon Pull-In',
    category: 'features',
    popularity: 144,
    tags: ['wagon', 'retro ride', 'weekend outing', 'family tour', 'retro charm'],
  }),
  createEmoji({
    id: 'garden-taxi-stand',
    emoji: '🚕',
    name: 'Garden Taxi Stand',
    category: 'features',
    popularity: 145,
    tags: ['taxi', 'city cab', 'pickup point', 'arrival lane', 'striped canopy'],
  }),
  createEmoji({
    id: 'parkway-patrol-watch',
    emoji: '🚓',
    name: 'Parkway Patrol Watch',
    category: 'features',
    popularity: 146,
    tags: ['police car', 'security detail', 'night patrol', 'beacon lights', 'safety escort'],
  }),
  createEmoji({
    id: 'rescue-ambulance-bay',
    emoji: '🚑',
    name: 'Rescue Ambulance Bay',
    category: 'features',
    popularity: 147,
    tags: ['ambulance', 'first aid', 'emergency ready', 'white stripe', 'lifeline'],
  }),
  createEmoji({
    id: 'firehouse-engine-post',
    emoji: '🚒',
    name: 'Firehouse Engine Post',
    category: 'features',
    popularity: 148,
    tags: ['fire engine', 'hydrant crew', 'scarlet truck', 'rescue route', 'sirens ready'],
  }),
  createEmoji({
    id: 'evening-shuttle-loop',
    emoji: '🚐',
    name: 'Evening Shuttle Loop',
    category: 'features',
    popularity: 149,
    tags: ['shuttle van', 'group tour', 'courtesy coach', 'arrival plaza', 'evening glow'],
  }),
  createEmoji({
    id: 'freight-drop-turnaround',
    emoji: '🚚',
    name: 'Freight Drop Turnaround',
    category: 'features',
    popularity: 150,
    tags: ['delivery truck', 'cargo bay', 'service lane', 'steel ramp', 'garden supply'],
  }),
  createEmoji({
    id: 'long-haul-rig-rest',
    emoji: '🚛',
    name: 'Long Haul Rig Rest',
    category: 'features',
    popularity: 151,
    tags: ['semi truck', 'rest stop', 'fuel plaza', 'cargo convoy', 'night headlights'],
  }),
  createEmoji({
    id: 'harvest-tractor-row',
    emoji: '🚜',
    name: 'Harvest Tractor Row',
    category: 'features',
    popularity: 152,
    tags: ['tractor', 'farm helper', 'fresh tilled', 'field groove', 'rural charm'],
  }),
  createEmoji({
    id: 'race-day-pit-lane',
    emoji: '🏎️',
    name: 'Race Day Pit Lane',
    category: 'features',
    popularity: 153,
    tags: ['racing car', 'pit crew', 'checkered flag', 'track ready', 'speedway flair'],
  }),
  createEmoji({
    id: 'rally-bike-corner',
    emoji: '🏍️',
    name: 'Rally Bike Corner',
    category: 'features',
    popularity: 154,
    tags: ['motorcycle', 'touring route', 'leaning turn', 'helmet gleam', 'road rally'],
  }),
  createEmoji({
    id: 'sunrise-scooter-run',
    emoji: '🛵',
    name: 'Sunrise Scooter Run',
    category: 'features',
    popularity: 155,
    tags: ['scooter', 'morning ride', 'café commute', 'city buzz', 'breezy lane'],
  }),
  createEmoji({
    id: 'cycle-share-hub',
    emoji: '🚲',
    name: 'Cycle Share Hub',
    category: 'features',
    popularity: 156,
    tags: ['bicycle', 'bike rack', 'pedal tour', 'eco travel', 'garden trail'],
  }),
  createEmoji({
    id: 'garden-rickshaw-ridge',
    emoji: '🛺',
    name: 'Garden Rickshaw Ridge',
    category: 'features',
    popularity: 157,
    tags: ['rickshaw', 'carriage ride', 'lantern tour', 'heritage lane', 'market melody'],
  }),
  createEmoji({
    id: 'skyline-monorail-glide',
    emoji: '🚝',
    name: 'Skyline Monorail Glide',
    category: 'features',
    popularity: 158,
    tags: ['monorail', 'elevated rail', 'sky bridge', 'panorama view', 'modern transit'],
  }),
  createEmoji({
    id: 'mountain-tram-platform',
    emoji: '🚞',
    name: 'Mountain Tram Platform',
    category: 'features',
    popularity: 159,
    tags: ['tram', 'ridge climb', 'vintage coach', 'alpine station', 'summit scene'],
  }),
  createEmoji({
    id: 'cable-car-lookout',
    emoji: '🚠',
    name: 'Cable Car Lookout',
    category: 'features',
    popularity: 160,
    tags: ['cable car', 'aerial view', 'suspended cabin', 'cliffside ride', 'skyline sweep'],
  }),
  createEmoji({
    id: 'gondola-summit-lift',
    emoji: '🚡',
    name: 'Gondola Summit Lift',
    category: 'features',
    popularity: 161,
    tags: ['gondola', 'peak tour', 'glacier glide', 'station perch', 'airy ascent'],
  }),
  createEmoji({
    id: 'pickup-truck-outpost',
    emoji: '🛻',
    name: 'Pickup Truck Outpost',
    category: 'features',
    popularity: 162,
    tags: ['pickup truck', 'tailgate camp', 'tool rack', 'trail supplies', 'weekend haul'],
  }),
  createEmoji({
    id: 'soccer-goal-kick',
    emoji: '⚽',
    name: 'Soccer Goal Kick',
    category: 'accents',
    popularity: 163,
    tags: ['soccer ball', 'garden pitch', 'team play', 'field sport', 'match day'],
  }),
  createEmoji({
    id: 'backboard-bounce-court',
    emoji: '🏀',
    name: 'Backboard Bounce Court',
    category: 'accents',
    popularity: 164,
    tags: ['basketball', 'hoop dreams', 'street court', 'orange rim', 'fast break'],
  }),
  createEmoji({
    id: 'gridiron-huddle-marker',
    emoji: '🏈',
    name: 'Gridiron Huddle Marker',
    category: 'accents',
    popularity: 165,
    tags: ['football', 'yard line', 'team huddle', 'goal post', 'game whistle'],
  }),
  createEmoji({
    id: 'bullpen-warmup-base',
    emoji: '⚾',
    name: 'Bullpen Warmup Base',
    category: 'accents',
    popularity: 166,
    tags: ['baseball', 'diamond dust', 'pitchers mound', 'home plate', 'foul line'],
  }),
  createEmoji({
    id: 'softball-sunrise-diamond',
    emoji: '🥎',
    name: 'Softball Sunrise Diamond',
    category: 'accents',
    popularity: 167,
    tags: ['softball', 'infield glow', 'league night', 'bat crack', 'bright laces'],
  }),
  createEmoji({
    id: 'twilight-tennis-service',
    emoji: '🎾',
    name: 'Twilight Tennis Service',
    category: 'accents',
    popularity: 168,
    tags: ['tennis ball', 'baseline rally', 'court stripes', 'match point', 'racket swing'],
  }),
  createEmoji({
    id: 'seaside-volley-set',
    emoji: '🏐',
    name: 'Seaside Volley Set',
    category: 'accents',
    popularity: 169,
    tags: ['volleyball', 'sand court', 'pepper drill', 'serve receive', 'sunny spike'],
  }),
  createEmoji({
    id: 'rugby-scrum-circle',
    emoji: '🏉',
    name: 'Rugby Scrum Circle',
    category: 'accents',
    popularity: 170,
    tags: ['rugby ball', 'scrum pack', 'touch line', 'stadium roar', 'team drive'],
  }),
  createEmoji({
    id: 'meadow-disc-flight',
    emoji: '🥏',
    name: 'Meadow Disc Flight',
    category: 'accents',
    popularity: 171,
    tags: ['flying disc', 'field toss', 'ultimate drift', 'hover arc', 'wind read'],
  }),
  createEmoji({
    id: 'goalie-net-guard',
    emoji: '🥅',
    name: 'Goalie Net Guard',
    category: 'accents',
    popularity: 172,
    tags: ['goal net', 'keeper stance', 'crease sweep', 'shootout', 'defense line'],
  }),
  createEmoji({
    id: 'ice-rink-breakaway',
    emoji: '🏒',
    name: 'Ice Rink Breakaway',
    category: 'accents',
    popularity: 173,
    tags: ['hockey stick', 'blue line', 'frozen rink', 'puck chase', 'goal lamp'],
  }),
  createEmoji({
    id: 'field-hockey-loop',
    emoji: '🏑',
    name: 'Field Hockey Loop',
    category: 'accents',
    popularity: 174,
    tags: ['field hockey', 'turf run', 'sweep shot', 'team drill', 'sideline cheer'],
  }),
  createEmoji({
    id: 'lacrosse-stick-stand',
    emoji: '🥍',
    name: 'Lacrosse Stick Stand',
    category: 'accents',
    popularity: 175,
    tags: ['lacrosse', 'crease dive', 'mesh pocket', 'fast break', 'sideline tape'],
  }),
  createEmoji({
    id: 'cricket-crease-call',
    emoji: '🏏',
    name: 'Cricket Crease Call',
    category: 'accents',
    popularity: 176,
    tags: ['cricket bat', 'wicket watch', 'crease chalk', 'tea break', 'pitch read'],
  }),
  createEmoji({
    id: 'table-tennis-spark',
    emoji: '🏓',
    name: 'Table Tennis Spark',
    category: 'accents',
    popularity: 177,
    tags: ['table tennis', 'spin serve', 'ping pong', 'fast rally', 'paddle snap'],
  }),
  createEmoji({
    id: 'badminton-feather-arc',
    emoji: '🏸',
    name: 'Badminton Feather Arc',
    category: 'accents',
    popularity: 178,
    tags: ['badminton', 'shuttle flight', 'net drop', 'clear shot', 'night court'],
  }),
  createEmoji({
    id: 'garden-ring-bout',
    emoji: '🥊',
    name: 'Garden Ring Bout',
    category: 'accents',
    popularity: 179,
    tags: ['boxing gloves', 'sparring bell', 'footwork', 'training ring', 'fight night'],
  }),
  createEmoji({
    id: 'dojo-discipline-hall',
    emoji: '🥋',
    name: 'Dojo Discipline Hall',
    category: 'accents',
    popularity: 180,
    tags: ['martial arts', 'belt rack', 'tatami mat', 'bow respect', 'kata flow'],
  }),
  createEmoji({
    id: 'curling-stone-slide',
    emoji: '🥌',
    name: 'Curling Stone Slide',
    category: 'accents',
    popularity: 181,
    tags: ['curling stone', 'sheet of ice', 'broom sweep', 'hammer shot', 'house rings'],
  }),
  createEmoji({
    id: 'handball-goal-sprint',
    emoji: '🤾',
    name: 'Handball Goal Sprint',
    category: 'accents',
    popularity: 182,
    tags: ['handball', 'court dash', 'goal zone', 'team press', 'quick pass'],
  }),
  createEmoji({
    id: 'acro-gym-circle',
    emoji: '🤸',
    name: 'Acro Gym Circle',
    category: 'accents',
    popularity: 183,
    tags: ['gymnastics', 'cartwheel', 'balance beam', 'spring floor', 'tumbling arc'],
  }),
  createEmoji({
    id: 'fencing-piste-poise',
    emoji: '🤺',
    name: 'Fencing Piste Poise',
    category: 'accents',
    popularity: 184,
    tags: ['fencing', 'foil salute', 'piste strip', 'en garde', 'parry riposte'],
  }),
  createEmoji({
    id: 'alpine-ski-line',
    emoji: '⛷️',
    name: 'Alpine Ski Line',
    category: 'accents',
    popularity: 185,
    tags: ['ski slope', 'powder trail', 'carving turn', 'mountain run', 'lift pass'],
  }),
  createEmoji({
    id: 'snowboard-ridge-drift',
    emoji: '🏂',
    name: 'Snowboard Ridge Drift',
    category: 'accents',
    popularity: 186,
    tags: ['snowboard', 'halfpipe', 'fresh snow', 'winter session', 'alpine air'],
  }),
  createEmoji({
    id: 'swim-lane-splash',
    emoji: '🏊',
    name: 'Swim Lane Splash',
    category: 'accents',
    popularity: 187,
    tags: ['swimming', 'lap lane', 'pool deck', 'goggles', 'cool plunge'],
  }),
  createEmoji({
    id: 'rowing-shell-crew',
    emoji: '🚣',
    name: 'Rowing Shell Crew',
    category: 'accents',
    popularity: 188,
    tags: ['rowing', 'oar stroke', 'river glide', 'coxswain call', 'team rhythm'],
  }),
  createEmoji({
    id: 'peloton-loop-track',
    emoji: '🚴',
    name: 'Peloton Loop Track',
    category: 'accents',
    popularity: 189,
    tags: ['cycling', 'loop course', 'draft line', 'hill climb', 'finish sprint'],
  }),
  createEmoji({
    id: 'archery-range-mark',
    emoji: '🏹',
    name: 'Archery Range Mark',
    category: 'accents',
    popularity: 190,
    tags: ['archery', 'target ring', 'bow string', 'steady aim', 'arrow flight'],
  }),
  createEmoji({
    id: 'riverbank-anglers-spot',
    emoji: '🎣',
    name: 'Riverbank Angler Spot',
    category: 'accents',
    popularity: 191,
    tags: ['fishing pole', 'quiet brook', 'bobber drift', 'fresh catch', 'streamside rest'],
  }),
  createEmoji({
    id: 'greenway-putting-cup',
    emoji: '⛳',
    name: 'Greenway Putting Cup',
    category: 'accents',
    popularity: 192,
    tags: ['golf green', 'flag pin', 'short game', 'gentle slope', 'birdie chance'],
  }),
  createEmoji({
    id: 'legendary-lettuce',
    emoji: '🥬',
    name: 'Legendary Lettuce',
    category: 'plants',
    popularity: 90,
    priceAnchorPercent: 0.5,
    cost: MAX_EMOJI_COST,
    tags: [
      { keyword: 'lettuce', aliases: ['leafy green', 'garden lettuce', 'salad green'] },
      'signature',
      'garden core',
      'clicker icon',
    ],
  }),
];

const gardenEmojiEntries: EmojiDefinition[] = [
  ...baseGardenEmojiEntries,
];

const sortedByPopularity = [...gardenEmojiEntries].sort((a, b) => a.popularity - b.popularity);
const totalEntries = sortedByPopularity.length;

const pricedByPopularity = sortedByPopularity.map((entry, index) => {
  const anchorPercent = PRICE_ANCHORS[entry.id];
  const percent =
    typeof anchorPercent === 'number'
      ? anchorPercent
      : totalEntries <= 1
      ? 0.5
      : index / (totalEntries - 1);
  return { ...entry, cost: computeBellCurveCost(percent) };
});

const priceMap = new Map(pricedByPopularity.map((entry) => [entry.id, entry.cost]));

export const gardenEmojiCatalog = gardenEmojiEntries.map((entry) => ({
  ...entry,
  cost: priceMap.get(entry.id) ?? computeBellCurveCost(0.5),
}));

const TRILLION = 1_000_000_000_000;
const BILLION = 1_000_000_000;
const MILLION = 1_000_000;

const trimTrailingZeros = (value: number) => {
  const fixed = value.toFixed(2);
  return fixed.replace(/\.0+$/, '').replace(/(\.[1-9])0$/, '$1');
};

export const formatClickValue = (value: number) => {
  if (value >= TRILLION) {
    return `${trimTrailingZeros(value / TRILLION)}T`;
  }

  if (value >= BILLION) {
    return `${trimTrailingZeros(value / BILLION)}B`;
  }

  if (value >= MILLION) {
    return `${trimTrailingZeros(value / MILLION)}M`;
  }

  if (value >= 1000) {
    return value.toLocaleString();
  }

  return `${Math.round(value)}`;
};

export const emojiCategoryOrder: Record<EmojiCategory, number> = {
  plants: 0,
  scenery: 1,
  creatures: 2,
  features: 3,
  accents: 4,
};

