export const MUSIC_OPTIONS = [
  {
    id: 'white-hush',
    name: 'White Hush',
    emoji: '🤍',
    description: 'A gentle static wash that brightens focus and energy.',
    family: 'white' as const,
  },
  {
    id: 'white-waves',
    name: 'White Waves',
    emoji: '🌊',
    description: 'Rolling broadband surf that keeps momentum moving.',
    family: 'white' as const,
  },
  {
    id: 'white-sparks',
    name: 'White Sparks',
    emoji: '✨',
    description: 'Shimmering tones that make the garden feel electric.',
    family: 'white' as const,
  },
  {
    id: 'grey-mist',
    name: 'Grey Mist',
    emoji: '🌫️',
    description: 'Balanced whispers of sound for calm concentration.',
    family: 'grey' as const,
  },
  {
    id: 'grey-embers',
    name: 'Grey Embers',
    emoji: '🔥',
    description: 'Warm crackles mixed with low hush for cozy evenings.',
    family: 'grey' as const,
  },
  {
    id: 'grey-lanterns',
    name: 'Grey Lanterns',
    emoji: '🏮',
    description: 'Soft drones and glowing chimes for twilight planting.',
    family: 'grey' as const,
  },
  {
    id: 'rain-mist',
    name: 'Rain Mist',
    emoji: '🌧️',
    description: 'Soft droplets on greenhouse glass for steady calm.',
    family: 'rain' as const,
  },
  {
    id: 'rain-thunder',
    name: 'Thunder Bloom',
    emoji: '⛈️',
    description: 'A sleepy storm with distant thunder rumbles.',
    family: 'rain' as const,
  },
  {
    id: 'ocean-tide',
    name: 'Moonlit Tides',
    emoji: '🌙',
    description: 'Slow tides and shimmering foam beneath the moon.',
    family: 'ocean' as const,
  },
  {
    id: 'ocean-depths',
    name: 'Deep Currents',
    emoji: '🐚',
    description: 'Subtle whale calls and gentle buoys far offshore.',
    family: 'ocean' as const,
  },
  {
    id: 'forest-dawn',
    name: 'Forest Dawn',
    emoji: '🌲',
    description: 'Birdsong and dew-kissed leaves greeting the sun.',
    family: 'forest' as const,
  },
  {
    id: 'forest-twilight',
    name: 'Twilight Grove',
    emoji: '🦉',
    description: 'Crickets and rustling branches after dusk settles.',
    family: 'forest' as const,
  },
  {
    id: 'static-amber',
    name: 'Amber Static',
    emoji: '📻',
    description: 'Vintage static with warm, cozy undertones.',
    family: 'static' as const,
  },
  {
    id: 'static-stars',
    name: 'Star Scanner',
    emoji: '🛰️',
    description: 'Spacey sweeps and distant signals for deep focus.',
    family: 'static' as const,
  },
  {
    id: 'keys-glass',
    name: 'Glass Keys',
    emoji: '🎹',
    description: 'Soft piano loops glimmering in the breeze.',
    family: 'keys' as const,
  },
  {
    id: 'keys-nocturne',
    name: 'Nocturne Notes',
    emoji: '🎼',
    description: 'Dusty chords and sleepy vinyl crackle.',
    family: 'keys' as const,
  },
  {
    id: 'night-orbit',
    name: 'Night Orbit',
    emoji: '🌌',
    description: 'Ambient synth pads that cradle the stars.',
    family: 'night' as const,
  },
  {
    id: 'night-halo',
    name: 'Lunar Halo',
    emoji: '🛌',
    description: 'Celestial hum that eases you into deep rest.',
    family: 'night' as const,
  },
] as const;

export type MusicOption = (typeof MUSIC_OPTIONS)[number];

export const MUSIC_AUDIO_MAP = {
  'white-hush': require('@/assets/audio/soft-soothing-deep-white-noise-378857.mp3'),
  'white-waves': require('@/assets/audio/heavy-rain-white-noise-159772.mp3'),
  'white-sparks': require('@/assets/audio/large-industrial-fan-running-constantly-in-warehouse-environment-339216.mp3'),
  'grey-mist': require('@/assets/audio/kitchen-fan-71401.mp3'),
  'grey-embers': require('@/assets/audio/fire-place-189399.mp3'),
  'grey-lanterns': require('@/assets/audio/street-ambience-traffic-410714.mp3'),
  'rain-mist': require('@/assets/audio/gentle-rain-for-relaxation-and-sleep-337279.mp3'),
  'rain-thunder': require('@/assets/audio/copyright-free-rain-sounds-331497.mp3'),
  'ocean-tide': require('@/assets/audio/rowing-river-sounds-215254.mp3'),
  'ocean-depths': require('@/assets/audio/river-sounds-420904.mp3'),
  'forest-dawn': require('@/assets/audio/chirping-birds-ambience-217410-1.mp3'),
  'forest-twilight': require('@/assets/audio/avala-trail-forest-nature-246779.mp3'),
  'static-amber': require('@/assets/audio/large-industrial-fan-running-constantly-in-warehouse-environment-339216.mp3'),
  'static-stars': require('@/assets/audio/soft-soothing-deep-white-noise-378857.mp3'),
  'keys-glass': require('@/assets/audio/river-sounds-420904.mp3'),
  'keys-nocturne': require('@/assets/audio/street-ambience-traffic-410714.mp3'),
  'night-orbit': require('@/assets/audio/soft-soothing-deep-white-noise-378857.mp3'),
  'night-halo': require('@/assets/audio/gentle-rain-for-relaxation-and-sleep-337279.mp3'),
} as const satisfies Record<MusicOption['id'], number>;

export const MUSIC_GROUPS = [
  { id: 'forest', label: 'Forest Echoes', intro: 'Leaves, birds, and twilight breezes between the vines.' },
  { id: 'static', label: 'Static & Signal', intro: 'Analog textures tuned for deep concentration.' },
  { id: 'keys', label: 'Keys & Chords', intro: 'Piano and plucked harmonies to soften the mood.' },
  { id: 'ocean', label: 'Ocean Waves', intro: 'Coastal hush and tidal sways for breezy focus.' },
  { id: 'white', label: 'White Noise', intro: 'Bright, energetic mixes to keep the garden lively.' },
  { id: 'grey', label: 'Grey Noise', intro: 'Softly balanced sounds that settle the senses.' },
  { id: 'rain', label: 'Rainfall Retreats', intro: 'Falling drops and distant thunder for gentle nights.' },
  { id: 'night', label: 'Night Sky', intro: 'Synth swells and starlit drones for restorative sleep.' },
] as const;

export type MusicGroup = (typeof MUSIC_GROUPS)[number];
